---
title: "Доменная модель"
description: "Информация по основным сущностям и агрегатам FLORA"
slug: ""
version: 1
weight: 3
draft: false
additional:
    author: "Панасюк Сергей"
    maintainer: "Панасюк Сергей"
    status: "in_work"
---

// titleIcon: "fa-solid fa-network-wired"

Раздел содержит основную информацию по основным сущностям и агрегатам FLORA.

> Подробная информация содержится в документе конкретного направления.

== Домены, агрегаты и сущности FLORA

{{<notice note>}}
Основные определения:

* **Доменная область** - совокупность агрегатов и сущностей, которые реализуют общие процессы.
* **Поддоменная область** - дополнительное разделение доменной области на составные части. Имеет отличный от других поддоменных областей набор агрегатов и функционал.
* **Агрегат** - совокупность сущностей, объединенных общим функционалом. Агрегат представляет собой группу связанных сущностей, которые рассматриваются как единое целое. Один объект (корневая сущность) внутри агрегата является корнем агрегата и служит точкой входа для доступа к другим объектам внутри агрегата. Агрегаты помогают гарантировать соблюдение бизнес-инвариантов, так как изменения внутри агрегата должны поддерживать консистентность данных в пределах этого агрегата ( мы сохраняем данные согласно определенной бизнес логике и не даем им нарушаться, следуя определенным правилам, и не позволяя другим частям программы ломать эти правила ).
* **Сущность** - набор атрибутов, которые описывают объект. Сущность обладает идентичностью, которая определяется ее уникальными атрибутами (обычно идентификатором). Сущности могут изменять свое состояние в течение их жизни. 
* **Объект-значение** - бизнес объект, не имеющий уникального идентификатора.

---

Основное отличие **Сущности** от **Объекта-значения** — это идентификатор. У Сущности есть идентификатор, у объекта-значения его нет. Идентификатор — это единственное свойство Сущности, которое определяет ее уникальность.

{{</notice>}}

```
FLORA - на текущий момент домен один
   |__ ДОМЕННАЯ_ОБЛАСТЬ
                    |__ ПОДДОМЕННАЯ_ОБЛАСТЬ
                                        |__ АГГРЕГАТ
                                                 |__ СУЩНОСТЬ
                                                           |__ АТТРИБУТЫ
                                                           |__ ОБЪЕКТ_ЗНАЧЕНИЕ
```


== Доменная модель

Доменные области распределены по смыслу. Всего используется 7 смысловых делений:

* **Core** - методы, используемые всеми доменными областями.
* **CRM** - по сути это тоже core-методы, методы, участвующие в коммуникации с клиентом.
* **ID** - хранилище данных о клиентах, пользователях, автомобилях и прочего. 
* **Experience** - наборы процессов для осуществления продажи.
* **External** - методы взаимодействия с внешними системами.
* **Internal** - методы взаимодействия с внутренними системами.
* **Payments** - методы для осуществления платежей.

---


[%inline,format=svg, width={width100}]
image::static/domain_model.svg[]




.*Miro схема сущностей*
[%collapsible%close]
====
++++
<iframe src="https://miro.com/app/board/uXjVNd7-0zo=/?moveToViewport=-11468,-5322,18358,9148&embedId=630865515434" width="100%" height="1000"></iframe>
++++
====
