[plantuml%interactive,"rolf",format=svg,align=center,width=100%]
.Rolf - Рольф
----
@startuml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml
!include static/includes/c4_component.puml

skinparam backgroundcolor transparent
skinparam minClassWidth 200
'skinparam linetype polyline
skinparam linetype ortho

LAYOUT_TOP_DOWN()

System_Ext(elt, "ELT", "ELT")
System_Ext(dadata, "Dadata", "Dadata")
System_Ext(tinkoff, "Tinkoff", "Tinkoff")

System_Boundary(rolf, "Рольф") {
    Person(user, "USER", "Пользователь")
    Person(admin, "ADMIN", "Администратор")
    System(flora, "FLORA", "FLORA", $link="/06_c4_infrastructure/01_flora_ext/")

    Rel(user, flora, "")
    Rel(admin, flora, "")
}

BiRel_D(rolf, elt, "")
BiRel_D(rolf, dadata, "")
BiRel_D(rolf, tinkoff, "")

@enduml
----
