[plantuml%interactive,"asp_sale",format=svg,align=center,width=30%]
.ASP Sale - Продажа автомобиля с пробегом
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(asp, "ASP", "Автомобили с пробегом", $link="/05_c4_workflow/02_experience/02_asp")
System(asp_sale, "ASP Sale", "Продажа автомобиля с пробегом")

Rel_U(asp_sale, asp, "")

@enduml
----

