[plantuml%interactive,"na",format=svg,align=center,width=30%]
.NA - Новые автомобили
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(experience, "Experience", "Прикладные методы", $link="/05_c4_workflow/02_experience/")

System(na, "NA", "Новые автомобили")
System(na_sale, "NA Sale", "Продажа нового автомобиля", $link="/05_c4_workflow/02_experience/03_na/01_na_sale/")

Rel_D(experience, na, "")
Rel_D(na, na_sale, "")

@enduml
----
