[plantuml%interactive,"keycloak",format=svg,align=center,width=30%]
.Keycloak - Keycloak
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(internal_integrations, "Internal integration", "Внутренние интеграции", $link="/05_c4/01_core/10_internal_integrations/")
System(keycloak, "Keycloak", "Keycloak")

Rel_U(keycloak, internal_integrations, "")

@enduml
----
