[plantuml%interactive,"asp",format=svg,align=center,width=75%]
.ASP - Автомобили с пробегом
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(experience, "Experience", "Прикладные методы", $link="/05_c4_workflow/02_experience/")

System(asp, "ASP", "Автомобили с пробегом")
System(asp_sale, "ASP Sale", "Продажа автомобиля с пробегом", $link="/05_c4_workflow/02_experience/02_asp/01_asp_sale/")
System(asp_buyout, "ASP Buyout", "Выкуп автомобиля с пробегом", $link="/05_c4_workflow/02_experience/02_asp/02_asp_buyout/")

Rel_D(experience, asp, "")
Rel_D(asp, asp_sale, "")
Rel_D(asp, asp_buyout, "")

@enduml
----
