[plantuml%interactive,"comments",format=svg,align=center,width=30%]
.Comments - Комментарии
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(coreapp, "Coreapp", "Комментарии, датагриды", $link="/05_c4_workflow/01_core/01_coreapp/")
System(comments, "Comments", "Комментарии")

Rel_U(comments, coreapp, "")

@enduml
----

