[plantuml%interactive,"events",format=svg,align=center,width=30%]
.Events - События
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(tasks_and_events, "Tasks and events", "Задачи, события и оповещения", $link="/05_c4_workflow/01_core/05_tasks_and_events/")
System(events, "Events", "Событие")

Rel_U(events, tasks_and_events, "")

@enduml
----

