[plantuml%interactive,"f_and_i_node",format=svg,align=center,width=30%]
.F&I - Страхование и финансовые продукты
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(f_and_i, "F&I", "Страхование и финансовые продукты", $link="/05_c4_workflow/02_experience/01_f_and_i/")
System(f_and_i_node, "F&I", "Страхование и финансовые продукты")

Rel_U(f_and_i_node, f_and_i, "")

@enduml
----

