default:
  tags:
    - com-dev

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote 
    
stages:
- build
- deploy

build:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_PROJECT_PATH
    DOCKER_IMAGE_VERSION: $CI_COMMIT_REF_NAME
    DOCKER_FILE_FOLDER: $CI_PROJECT_DIR/themes/template
    DOCKER_REGISTRY_HOST: docker-rolf.registry.int.rolfcorp.ru
  image:
    name: docker.registry.int.rolfcorp.ru/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ""
  before_script:
  - |
    build () {
      TAG=$(echo $DOCKER_IMAGE_VERSION | sed "s/[^[:alnum:]\.\_\-]/-/g" | tr "[:upper:]" "[:lower:]")
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $DOCKER_FILE_FOLDER/Dockerfile \
        --destination $DOCKER_REGISTRY_HOST/$DOCKER_IMAGE_NAME:$TAG \
        --build-arg DOCKER_PROXY_HOST_1=$DOCKER_PROXY_HOST \
        --build-arg DOCKER_CUSTOM_PROXY_HOST=$DOCKER_PROXY_HOST \
        --image-name-tag-with-digest-file=docker-image-full-name \
        --skip-tls-verify \
        --push-retry=5 \
        --image-fs-extract-retry=5 \
        $@
    }
  artifacts:
    paths:
    - docker-image-full-name
  tags:
  - com-dev
  only:
    - main
    - tags
    - preprod
    - /^feat/.*$/
  script: |
    build \
      --build-arg HUGO_BASE_URL=https://doc-system-architecture-main.com-dev.int.rolfcorp.ru/ \
      --build-arg NPM_TOKEN=$NPM_TOKEN 

deploy:
  stage: deploy
  image: docker.registry.int.rolfcorp.ru/curlimages/curl:7.69.1
  variables:
    SERVICE: doc
    PROJECT: system-architecture
  script: |
    touch YQLINES
    ENV=$(echo $CI_COMMIT_REF_NAME | sed "s/[^[:alnum:]_]//g" | sed "s/feat//g" | tr "[:upper:]" "[:lower:]")
    echo ".app.$SERVICE.image=\"$(cat docker-image-full-name)\"" >> YQLINES
    echo ".app.$SERVICE.secret.key=\"$PROJECT/dev/$ENV/$SERVICE\"" >> YQLINES
    curl -k -X POST \
      -F token=$TOKEN_DEPLOY_TRIGGER \
      -F ref=main \
      -F "variables[YQLINES]=$(cat YQLINES)" \
      -F "variables[PROJECT]=$PROJECT" \
      -F "variables[ENV]=$ENV" \
      -F "variables[SERVICE]=$SERVICE" \
      https://gitlab.int.rolfcorp.ru/api/v4/projects/$ID_DEPLOY_PROJECT/trigger/pipeline
  only:
    - main
    - preprod
    - /^feat/.*$/
