baseURL = "https://example.com"
timeout = "10m"

languageCode = "RU-ru"
DefaultContentLanguage = "ru"
title = "Архитектура ПО FLORA"
theme = "shadocs"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "ru"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
enableGitInfo = true
buildDrafts = true

[taxonomies]
    # categories = 'Categories'
    # tags = 'Tags'
    categories = 'Categories'
    tags = 'Tags'
    types = 'Types'

[params]
    # Source Code repository section

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]
    github_doc_repository = "https://gitlab.int.rolfcorp.ru/one-rolf/doc/core"

    # Image file path displayed during a 404 error
    image404 = "images/404.gif"

    # Favicon website file path
    favicon = "images/favicon.png"

    # Default layout used for the homepage
    # homeLayout = "onboarding"

    # Site content order (https://gohugo.io/templates/lists/#order-content)
    siteContentOrder = "weight"

    # Activate/Deactivate the table of contents globally (sitewide)
    toc = true

    # Taxonomies list
    # For each taxonomy following keys can be sets:
    # - icon = "Fontawesome classes associated to the taxonomy"
    [params.taxonomies]
        [params.taxonomies.categories]
            icon = "fa-solid fa-table-cells"
        [params.taxonomies.tags]
            icon = "fa-solid fa-tag"
        #[params.taxonomies.types]
        #    icon = "fa-solid fa-text"

    # Верхнее меню
    # [params.topmenu]
    #     [params.topmenu.1_overview]
    #         id = 'overview'
    #         name = 'Общая информация'
    #         url = '/01_overview/'
    #         icon = 'fa-sharp fa-solid fa-circle-info'
    #     [params.topmenu.2_info_model]
    #         id = 'info_model'
    #         name = 'Информационная модель'
    #         url = '/02_info_model/'
    #         icon = 'fa-solid fa-network-wired'

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
    [markup.asciidocExt]
        backend = 'html5'
        extensions = ["asciidoctor-html5s", "asciidoctor-diagram", "asciidoctor-pdf"]
        # extensions = ["asciidoctor-html5s", "asciidoctor-diagram", "asciidoctor-rouge", "asciidoctor-pdf"]
        # extensions = ["asciidoctor-diagram"]
        # failureLevel = 'fatal'
        # noHeaderOrFooter = true
        # preserveTOC = false
        # safeMode = 'unsafe'
        # sectionNumbers = false
        # trace = false
        # verbose = false
        # workingFolderCurrent = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "content",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^asciidoctor$']
    osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']