[plantuml%interactive,"pfanalyze",format=svg,align=center,width=20%]
.Print forms analyze - Анализ печатных форм
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(core, "Core", "Общий функционал", $link="/05_c4/01_core/")
System(pfanalyze, "Print forms analyze", "Анализ печатных форм")
System(pfanalyzing, "Print forms analyze", "Анализ печатных форм", $link="/05_c4/01_core/12_pfanalyze/01_pfanalyzing/")

Rel_D(core, pfanalyze, "")
Rel_D(pfanalyze, pfanalyzing, "")

@enduml
----
