@startuml client record approval

title "Согласование записи клиента на приемку"



' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

Container_Boundary(b,""){
    System('kafka_serviceCalendarSlotTask', 'kafka_serviceCalendarSlotTask')
    DomainEvent('ЗадачаЗаписьКлиентаЗакрыта', 'Задача "Запись клиента" закрыта')
    Aggregate('Task1', 'Task')
    Policy('ДолжнаБытьСозданаЗадачаДождатьсяКлиента', 'Должна быть создана задача "Дождаться клиента"')
    Command('СоздатьЗадачу', 'Создать задачу')
    DomainEvent('ЗадачаДождатьсяКлиентаСоздана', 'Задача "Дождаться клиента" создана')
    Aggregate('Task2', 'Task')
}

'yellow
Person('СПРК1', 'СПРК')
Person('СПРК2', 'СПРК')
Person('СПРК3', 'СПРК')
Person('СПРК4', 'СПРК')

'blue
Command('ПерейтиВЭкранРаботыиЗапчасти', 'Перейти в экран "Работы и запчасти"')
Command('НажатьКнопкуРезерв', 'Нажать кнопку "Резерв"')
Command('ЗаписатьНаПриемку', 'Записать на приемку')
Command('ЗакрытьЗадачу', 'Закрыть задачу')
Command('РаспечататьПропуск', 'Распечатать пропуск')
Command('ПоменятьСтатус', 'Поменять статус')

'pink
System('UICommand', 'UI Command')
System('oracle_goodsReserve_v2', 'oracle_goodsReserve_v2')
System('postCalendarSlot_v2', 'postCalendarSlot_v2')
System('createLegalDocument', 'createLegalDocument')
System('generatePdfForLegalDocument', 'generatePdfForLegalDocument')
System('pforms_getPDF', 'pforms_getPDF')
System('signLegalDocument', 'signLegalDocument')
System('uploadSignedLegalDocument', 'uploadSignedLegalDocument')

'fiolet
Policy('КлиентДолженДатьСогласиеилиПодписатьПЗН', 'Клиент должен дать согласие или подписать ПЗН')
Policy('ДолженБытьПроставленРезервВСистемеОстатков', 'Должен быть проставлен резерв в системе остатков')
Policy('ДолжнаБытьЗакрытаЗадачаЗаписьКлиента', 'Должна быть закрыта задача "Запись клиента"')
Policy('УДокументаДолженБытьИзмененСтатус', 'У документа должен быть изменен статус')

DomainEvent('КлиентДалСогласиеилиПодписалПЗН', 'Клиент дал согласие или подписал ПЗН')
DomainEvent('ОткрылсяЭкранРаботыиЗапчасти', 'Открылся экран "Работы и запчасти"')
DomainEvent('ЗЧЗарезеервированы', 'ЗЧ зарезервированы')
DomainEvent('ЗаписьВКалендареСоздана', 'Запись в календаре создана')
DomainEvent('ЮридическийДокументВизиткаПропускНаВъездСоздан', 'Юридический документ "Визитка/Пропуск на въезд" создан')
DomainEvent('ЮридическийДокументВизиткаПропускНаВъездРаспечатан', 'Юридический документ "Визитка/Пропуск на въезд" распечатан')
DomainEvent('СПРКПодписалПропускиПоставилПечать', 'СПРК подписал пропуск и поставил печать')
DomainEvent('ЮридическийДокументВизиткаПропускНаВъездПодписан', 'Юридический документ "Визитка/Пропуск на въезд" подписан')
DomainEvent('КлиентПолучилПропуск', 'Клиент получил пропуск')


'green
UserInterface('ЭкранРаботыиЗапчасти', 'Экран "Работы и запчасти"')
UserInterface('ЭкранШагЗаписьКлиента', 'Экран шаг "Запись клиента"')
UserInterface('КнопкаСоздатьВизиткаПропускНаВъезд', 'Кнопка "Создать Визитка/Пропуск на въезд"')

Aggregate('LegalDocument1', 'Legal Document')
Aggregate('LegalDocument2', 'Legal Document')
Aggregate('LegalDocument3', 'Legal Document')


КлиентДолженДатьСогласиеилиПодписатьПЗН--КлиентДалСогласиеилиПодписалПЗН
КлиентДалСогласиеилиПодписалПЗН--ДолженБытьПроставленРезервВСистемеОстатков
ДолженБытьПроставленРезервВСистемеОстатков--СПРК1
СПРК1--ПерейтиВЭкранРаботыиЗапчасти
ПерейтиВЭкранРаботыиЗапчасти--UICommand
UICommand--ОткрылсяЭкранРаботыиЗапчасти
ОткрылсяЭкранРаботыиЗапчасти--ЭкранРаботыиЗапчасти
ЭкранРаботыиЗапчасти--СПРК2
СПРК2--НажатьКнопкуРезерв
НажатьКнопкуРезерв--oracle_goodsReserve_v2
oracle_goodsReserve_v2--ЗЧЗарезеервированы
ЗЧЗарезеервированы--ЭкранШагЗаписьКлиента
ЭкранШагЗаписьКлиента--СПРК3
СПРК3--ЗаписатьНаПриемку
ЗаписатьНаПриемку--postCalendarSlot_v2
postCalendarSlot_v2--ЗаписьВКалендареСоздана
ЗаписьВКалендареСоздана--ДолжнаБытьЗакрытаЗадачаЗаписьКлиента
ДолжнаБытьЗакрытаЗадачаЗаписьКлиента--ЗакрытьЗадачу
ЗакрытьЗадачу--kafka_serviceCalendarSlotTask
kafka_serviceCalendarSlotTask--ЗадачаЗаписьКлиентаЗакрыта

ЗаписьВКалендареСоздана-->kafka_serviceCalendarSlotTask
  
ЗадачаЗаписьКлиентаЗакрыта .. Task1
Task1 .. ДолжнаБытьСозданаЗадачаДождатьсяКлиента

ДолжнаБытьСозданаЗадачаДождатьсяКлиента--СоздатьЗадачу
СоздатьЗадачу--ЗадачаДождатьсяКлиентаСоздана

ЗадачаДождатьсяКлиентаСоздана .. Task2
Task2 .. КнопкаСоздатьВизиткаПропускНаВъезд

КнопкаСоздатьВизиткаПропускНаВъезд--СПРК4
СПРК4--РаспечататьПропуск
РаспечататьПропуск--createLegalDocument
createLegalDocument--ЮридическийДокументВизиткаПропускНаВъездСоздан

ЮридическийДокументВизиткаПропускНаВъездСоздан .. LegalDocument1
LegalDocument1 .. generatePdfForLegalDocument

generatePdfForLegalDocument--pforms_getPDF
pforms_getPDF--ЮридическийДокументВизиткаПропускНаВъездРаспечатан

ЮридическийДокументВизиткаПропускНаВъездРаспечатан .. LegalDocument2
LegalDocument2 .. СПРКПодписалПропускиПоставилПечать

СПРКПодписалПропускиПоставилПечать--УДокументаДолженБытьИзмененСтатус
УДокументаДолженБытьИзмененСтатус--ПоменятьСтатус
ПоменятьСтатус--signLegalDocument
ПоменятьСтатус--uploadSignedLegalDocument
signLegalDocument--ЮридическийДокументВизиткаПропускНаВъездПодписан
uploadSignedLegalDocument--ЮридическийДокументВизиткаПропускНаВъездПодписан

ЮридическийДокументВизиткаПропускНаВъездПодписан .. LegalDocument3
LegalDocument3 .. КлиентПолучилПропуск

@enduml