@startuml client record approval

title "Завершение сделки"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

'yellow
Person('СПРК1', 'СПРК')
Person('СПРК2', 'СПРК')
Person('СПРК3', 'СПРК')
Person('СПРК4', 'СПРК')


'blue
Command('ПереходвЭкранШагПередачаТСКлиенту', 'Переход в Экран/шаг "Передача Т/С клиенту"')
Command('ПоменятьСтатус', 'Поменять статус')
Command('ПерейтинаэкраншагЗавершениеСделки', 'Перейти на экран / шаг "Завершение сделки"')
Command('ЗавершитьСделку', 'Завершить сделку')
Command('ОбновитьСтатус1', 'Обновить статус')
Command('ОбновитьСтатус2', 'Обновить статус')



'pink
System('UICommand1', 'UI Command')
System('UICommand2', 'UI Command')
System('UICommand3', 'UI Command')
System('signLegalDocument', 'signLegalDocument')
System('uploadSignedLegalDocument', 'uploadSignedLegalDocument')
System('updateLegalEventClearance', 'updateLegalEventClearance')
System('updateLegalExecutionComplete', 'updateLegalExecutionComplete')
System('kafka_serviceLegalEventsEvents', 'kafka_serviceLegalEventsEvents')


'fiolet
Policy('АППВыполненныхРаботДолженБытьПодписан', '"АПП выполненных работ" должен быть подписан')
Policy('УДокументаДолженБытьИзмененСтатус', 'У документа должен быть изменен статус')
Policy('ДолжнаБытьЗавершенаЮридическаяЧастьСделки', 'Должна быть завершена юридическая часть сделки')
Policy('ДолжнаБытьЗакрытаЗадачаПередачатсКлиенту', 'Должна быть закрыта задача "Передача т/с клиенту"')




DomainEvent('ДоступнакнопкаПродолжить', 'Доступна кнопка "Продолжить"')
DomainEvent('ОткрылсяЭкранПередачаТСКлиенту', 'Открылся экран "Передача Т/С клиенту"')
DomainEvent('КлиентиСПРКПодписалиАППВыполненныхРабот', 'Клиент и СПРК подписали "АПП выполненных работ"')
DomainEvent('ЮридическийДокументАППВыполненныхРаботПодписанКлиентомиСПРК', 'Юридический документ "АПП выполненных работ" подписан клиентом и СПРК')
DomainEvent('ОткрылсяЭкранЗавершениеСделки', 'Открылся экран "Завершение сделки"')
DomainEvent('ЮридическоеСобытиеПодтвержденоИсполнениеПерешловСтатусОформлениеЗавершено', 'Юридическое событие "Подтверждено исполнение" перешло в статус "Оформление завершено"')
DomainEvent('АвтомобильуКлиента', 'Автомобиль у клиента')
DomainEvent('ПользовательОтметилчтоАвтомобильуКлиента', 'Пользователь отметил, что "автомобиль у клиента"')
DomainEvent('ЮридическоесобытиеПодтвержденоИсполнениеПерешловСтатусЗавершеноИсполнение', 'Юридическое событие "Подтверждено исполнение" перешло в статус "Завершено исполнение"')
DomainEvent('ЗакрытаЗадачаПередачатсКлиенту', 'Закрыта задача "Передача т/с клиенту"')
DomainEvent('ПредложенияиПотребностьПереведенывИсполнено', 'Предложения и потребность переведены в "Исполнено"')
DomainEvent('ПотребностьПерешлавСтатусВыполнено', 'Потребность перешла в статус "Выполнено"')




'grenn
UserInterface('ТостШагПередачаТСклиентуРазблокирован', 'Тост "Шаг" Передача Т/С клиенту" разблокирован"')
UserInterface('ЭкраПередачаТСКлиенту', 'Экран "Передача Т/С клиенту"')
UserInterface('ОкноНеобходимоПодтвердитьПодписаниеДокумента', 'Окно "Необходимо подтвердить подписание документа"')
UserInterface('ТостШагЗавершениеСделкиразблокирован', 'Тост "Шаг" Завершение сделки "разблокирован"')
UserInterface('КнопкаАвтомобильуКлиента', 'Кнопка "автомобиль у клиента"')



Aggregate('LegalDocument', 'Legal Document')
Aggregate('LegalEvent1', 'Legal Event')
Aggregate('LegalEvent2', 'Legal Event')
Aggregate('Task', 'Task')
Aggregate('Need1', 'Need')
Aggregate('Need2', 'Need')
Aggregate('Order', 'Order')

ДоступнакнопкаПродолжить--ТостШагПередачаТСклиентуРазблокирован
ТостШагПередачаТСклиентуРазблокирован--СПРК1
СПРК1--ПереходвЭкранШагПередачаТСКлиенту
ПереходвЭкранШагПередачаТСКлиенту--UICommand1
UICommand1--ОткрылсяЭкранПередачаТСКлиенту
ОткрылсяЭкранПередачаТСКлиенту--ЭкраПередачаТСКлиенту
ЭкраПередачаТСКлиенту--АППВыполненныхРаботДолженБытьПодписан
АППВыполненныхРаботДолженБытьПодписан--КлиентиСПРКПодписалиАППВыполненныхРабот
КлиентиСПРКПодписалиАППВыполненныхРабот--УДокументаДолженБытьИзмененСтатус
УДокументаДолженБытьИзмененСтатус--ОкноНеобходимоПодтвердитьПодписаниеДокумента
ОкноНеобходимоПодтвердитьПодписаниеДокумента--СПРК2
СПРК2--ПоменятьСтатус
ПоменятьСтатус--signLegalDocument
ПоменятьСтатус--uploadSignedLegalDocument
uploadSignedLegalDocument--ЮридическийДокументАППВыполненныхРаботПодписанКлиентомиСПРК
signLegalDocument--ЮридическийДокументАППВыполненныхРаботПодписанКлиентомиСПРК

ЮридическийДокументАППВыполненныхРаботПодписанКлиентомиСПРК .. LegalDocument
LegalDocument .. ТостШагЗавершениеСделкиразблокирован

ТостШагЗавершениеСделкиразблокирован--СПРК3
СПРК3--ПерейтинаэкраншагЗавершениеСделки
ПерейтинаэкраншагЗавершениеСделки--UICommand2
UICommand2--ОткрылсяЭкранЗавершениеСделки
ОткрылсяЭкранЗавершениеСделки--updateLegalEventClearance
updateLegalEventClearance--ЮридическоеСобытиеПодтвержденоИсполнениеПерешловСтатусОформлениеЗавершено

ЮридическоеСобытиеПодтвержденоИсполнениеПерешловСтатусОформлениеЗавершено .. LegalEvent1
LegalEvent1 .. АвтомобильуКлиента

АвтомобильуКлиента--КнопкаАвтомобильуКлиента
КнопкаАвтомобильуКлиента--СПРК4
СПРК4--ЗавершитьСделку
ЗавершитьСделку--UICommand3
UICommand3--ПользовательОтметилчтоАвтомобильуКлиента
ПользовательОтметилчтоАвтомобильуКлиента--ДолжнаБытьЗавершенаЮридическаяЧастьСделки
ДолжнаБытьЗавершенаЮридическаяЧастьСделки--ОбновитьСтатус1
ОбновитьСтатус1--updateLegalExecutionComplete
updateLegalExecutionComplete--ЮридическоесобытиеПодтвержденоИсполнениеПерешловСтатусЗавершеноИсполнение

ЮридическоесобытиеПодтвержденоИсполнениеПерешловСтатусЗавершеноИсполнение .. LegalEvent2
LegalEvent2 .. ДолжнаБытьЗакрытаЗадачаПередачатсКлиенту

ЮридическоесобытиеПодтвержденоИсполнениеПерешловСтатусЗавершеноИсполнение-->kafka_serviceLegalEventsEvents

ДолжнаБытьЗакрытаЗадачаПередачатсКлиенту--ОбновитьСтатус2
ОбновитьСтатус2--kafka_serviceLegalEventsEvents
kafka_serviceLegalEventsEvents--ЗакрытаЗадачаПередачатсКлиенту

ЗакрытаЗадачаПередачатсКлиенту .. Task
Task .. ПредложенияиПотребностьПереведенывИсполнено

ПредложенияиПотребностьПереведенывИсполнено .. Need1
ПредложенияиПотребностьПереведенывИсполнено .. Order

ПредложенияиПотребностьПереведенывИсполнено--ПотребностьПерешлавСтатусВыполнено

ПотребностьПерешлавСтатусВыполнено .. Need2

@enduml