@startuml distribution of work

title "Распределение выполненных работ по заказ-нарядам"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

'yellow
Person('СПРК1', 'СПРК')
Person('СПРК2', 'СПРК')
Person('СПРК3', 'СПРК')
Person('СПРК4', 'СПРК')

'blue
Command('ПереходвЭкраншагРаспределениеРаботПозаказнарядам', 'Переход в Экран/шаг "Распределение работ по заказ-нарядам"')
Command('ОткрытьСписокРабот', 'Открыть список работ')
Command('РаспределитьРаботы', 'Распределить работы по ЗН')
Command('НажатьГалочку', 'Нажать галочку')
Command('ЗакрытьЗадачу', 'Закрыть задачу')


'pink
System('UICommand1', 'UI Command')
System('getNeedAndOrders', 'getNeedAndOrders')
System('updateOrders', 'updateOrders')
System('UICommand2', 'UI Command')
System('closeTask', 'closeTask')


'fiolet
Policy('ДолжнаБытьЗакрытаЗадачаРаспределениеРаботпоЗН', 'Должна быть закрыта задача "Распределение работ по З/Н"')


DomainEvent('ПереходОсуществлен', 'Переход осуществлен')
DomainEvent('РаботыиЗапчастиРаспределеныпоЗаказНарядам', 'Работы и запчасти распределены по заказ-нарядам')
DomainEvent('ГалочкаЗаполнена', 'Галочка заполнена')
DomainEvent('ЗадачаРаспределениеРаботпознЗакрыта', 'Задача "Распределение работ по з/н" закрыта')
DomainEvent('ЗадачаПодготовкаДокументовСоздана', 'Задача "Подготовка документов" создана')


'grenn
UserInterface('ТостШагРаспределениеРаботПоЗаказнарядамРазблокирован', 'Тост "Шаг" Распределение работ по заказ-нарядам "разблокирован"')
UserInterface('ЭкранШагРаспределениеРаботпозаказнарядам', 'Экран/шаг "Распределение работ по заказ-нарядам"')
UserInterface('ЭкранРаботыиЗапчасти', 'Экран "Работы и запчасти"')
UserInterface('КнопкаЯПроверилСписокРаботиНаполнениезаказнарядов', 'Кнопка "Я проверил список работ и наполнение заказ-нарядов"')

Aggregate('Order', 'Order')
Aggregate('Task1', 'Task')
Aggregate('Task2', 'Task')

ТостШагРаспределениеРаботПоЗаказнарядамРазблокирован--СПРК1
СПРК1--ПереходвЭкраншагРаспределениеРаботПозаказнарядам
ПереходвЭкраншагРаспределениеРаботПозаказнарядам--UICommand1
UICommand1--ПереходОсуществлен
ПереходОсуществлен--ЭкранШагРаспределениеРаботпозаказнарядам
ЭкранШагРаспределениеРаботпозаказнарядам--СПРК2
СПРК2--ОткрытьСписокРабот
ОткрытьСписокРабот--getNeedAndOrders
getNeedAndOrders--ЭкранРаботыиЗапчасти
ЭкранРаботыиЗапчасти--СПРК3
СПРК3--РаспределитьРаботы
РаспределитьРаботы--updateOrders
updateOrders--РаботыиЗапчастиРаспределеныпоЗаказНарядам

РаботыиЗапчастиРаспределеныпоЗаказНарядам .. Order
Order .. КнопкаЯПроверилСписокРаботиНаполнениезаказнарядов

КнопкаЯПроверилСписокРаботиНаполнениезаказнарядов--СПРК4
СПРК4--НажатьГалочку
НажатьГалочку--UICommand2
UICommand2--ГалочкаЗаполнена
ГалочкаЗаполнена--ДолжнаБытьЗакрытаЗадачаРаспределениеРаботпоЗН
ДолжнаБытьЗакрытаЗадачаРаспределениеРаботпоЗН--ЗакрытьЗадачу
ЗакрытьЗадачу--closeTask

closeTask--ЗадачаРаспределениеРаботпознЗакрыта
ЗадачаРаспределениеРаботпознЗакрыта .. Task1
Task1 .. ЗадачаПодготовкаДокументовСоздана
ЗадачаПодготовкаДокументовСоздана .. Task2


@enduml