@startuml driver_task

title "Запись А/М в цех и создание Задачи на перегонщика"

' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

'yellow
Person('MK', 'MK')

'blue
Command('ЗаписатьВЦех', 'Записать в цех')
Command('ВыбратьИсполнителя', 'Выбрать исполнителя')
Command('СоздатьЗадачу', 'Создать задачу')

'pink
System('updateLegalEventClearance','updateLegalEventClearance')
System('postCalendarSlotv2','postCalendarSlot_v2')
System('getusers','getUsers')
System('createtask','createTask')

DomainEvent('ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусОформлениеЗавершено', 'Юридическое событие "Заключёно предварительное соглашение" перешло в статус "Оформление завершено"')
DomainEvent('РольфПолучилКлючиотАМ','Рольф получил ключи от А/М')
DomainEvent('ЗаписьвКалендареСоздана','Запись в календаре  создана')
DomainEvent('ИсполнительВыбран','Исполнитель выбран')
DomainEvent('ЗадачаНаПрегонщикаСоздана','Задача "На прегонщика" создана')


'fiolet
Policy('НеобходимоЗаписатьАМвЦехИнаВыдачу', 'Необходимо записать А/М в цех и на выдачу')
Policy('НеобходимоВыбратьИсполнителяДляЗадачаНаПерегонщика', 'Необходимо выбрать исполнителя для "Задача на перегонщика"')
Policy('ДолжнаБытьСозданаЗадачаНаПерегонщика', 'Должна быть создана "Задача на перегонщика"')

'grenn
UserInterface('ЭкранШагЗаписьвЦех', 'Экран/шаг "Запись в цех"')


Aggregate('LegalEvent', 'Legal Event')
Aggregate('Task','Task')


updateLegalEventClearance--ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусОформлениеЗавершено
 

ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусОформлениеЗавершено .. LegalEvent
LegalEvent .. РольфПолучилКлючиотАМ

  

РольфПолучилКлючиотАМ--НеобходимоЗаписатьАМвЦехИнаВыдачу
НеобходимоЗаписатьАМвЦехИнаВыдачу--ЭкранШагЗаписьвЦех
ЭкранШагЗаписьвЦех--MK
MK--ЗаписатьВЦех
ЗаписатьВЦех--postCalendarSlotv2
postCalendarSlotv2--ЗаписьвКалендареСоздана
ЗаписьвКалендареСоздана--НеобходимоВыбратьИсполнителяДляЗадачаНаПерегонщика
НеобходимоВыбратьИсполнителяДляЗадачаНаПерегонщика--ВыбратьИсполнителя
ВыбратьИсполнителя--getusers
getusers--ИсполнительВыбран
ИсполнительВыбран--ДолжнаБытьСозданаЗадачаНаПерегонщика
ДолжнаБытьСозданаЗадачаНаПерегонщика--СоздатьЗадачу
СоздатьЗадачу--createtask
createtask--ЗадачаНаПрегонщикаСоздана

  
ЗадачаНаПрегонщикаСоздана .. Task


@enduml