@startuml endKP

title "Завершение юридического события Предоставлено КП"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

Container_Boundary(container1, "") {
    System('kafka_serviceLegalEventsEventsConsumer1', 'kafka_serviceLegalEventsEventsConsumer')
    DomainEvent('ЗадачаПодписатьизагрузитьПЗНЗакрыта','Задача "Подписать и загрузить ПЗН" закрыта')
    Aggregate('Task1','Task')
}

Container_Boundary(container2, "") {
    System('kafka_serviceLegalEventsEventsConsumer2', 'kafka_serviceLegalEventsEventsConsumer')
    DomainEvent('ЗадачаПриемкаТССоздана','Задача "Приемка ТС" создана')
    Aggregate('Task2','Task')
}


'yellow
Person('СПРК', 'СПРК')


'blue
Command('ПеревестиЮридическогоСобытиевСтатусОформлениеЗавершено', 'Перевести  Юридического событие в статус "Оформление завершено"')
Command('ЗакрытьЗадачу', 'Закрыть задачу')
Command('ПеревестиЮридическоеСобытивСтатусЗавершеноИсполнение', 'Перевести  Юридическое событие в статус "Завершено исполнение"')
Command('СоздатьЗадачу', 'Создать задачу')


'pink
System('updateLegalEventClearance', 'updateLegalEventClearance')
System('updateLegalExecutionComplete', 'updateLegalExecutionComplete')
DomainEvent('ЮридическоеСобытиеПредоставленоКППерешловСтатусОформлениеЗавершено', 'Юридическое событие "Предоставлено КП" перешло в статус "Оформление завершено"')
DomainEvent('РольфПолучилПредоплатуИлиВыполнилисьДругиеУсловия','Рольф получил предоплату или выполнились другие условия')
DomainEvent('ЮридическоеСобытиеПредоставленоКПперешловСтатусЗавершеноИсполнение','Юридическое событие "Предоставлено КП" перешло в статус "Завершено исполнение"')
DomainEvent('ПредложенияПерешлиВСтадиюКоммерческоеПредложение','Предложения перешли в стадию "коммерческое предложение"')


'fiolet
Policy('ДолжнаБытьЗакрытаЗадачаПодписатьиЗагрузитьПЗН', 'Должна быть закрыта задача "Подписать и загрузить ПЗН"')
Policy('НеобходимоЗавеериштьЮридическоеСобытиеПродвинутьСделку', 'Необходимо завершить юридическое событие (продвинуть сделку)')
Policy('ДолжнаБытьЗакрытаЗадачаДанныеОКлиентеИАвто', 'Должна быть создана задача "Наполнение работ и ЗЧ"')

'grenn
UserInterface('КнопкаПродолжить', 'Кнопка "Продолжить"')


Aggregate('LegalEvent1', 'Legal Event')
Aggregate('LegalEvent2', 'Legal Event')
Aggregate('Order1', 'Order')




КнопкаПродолжить--СПРК
СПРК--ПеревестиЮридическогоСобытиевСтатусОформлениеЗавершено
ПеревестиЮридическогоСобытиевСтатусОформлениеЗавершено--updateLegalEventClearance
updateLegalEventClearance--ЮридическоеСобытиеПредоставленоКППерешловСтатусОформлениеЗавершено

ЮридическоеСобытиеПредоставленоКППерешловСтатусОформлениеЗавершено .. LegalEvent1
LegalEvent1 .. ДолжнаБытьЗакрытаЗадачаПодписатьиЗагрузитьПЗН

ЮридическоеСобытиеПредоставленоКППерешловСтатусОформлениеЗавершено-->kafka_serviceLegalEventsEventsConsumer1

ДолжнаБытьЗакрытаЗадачаПодписатьиЗагрузитьПЗН--ЗакрытьЗадачу
ЗакрытьЗадачу--kafka_serviceLegalEventsEventsConsumer1
kafka_serviceLegalEventsEventsConsumer1--ЗадачаПодписатьизагрузитьПЗНЗакрыта

ЗадачаПодписатьизагрузитьПЗНЗакрыта .. Task1
Task1 .. РольфПолучилПредоплатуИлиВыполнилисьДругиеУсловия

РольфПолучилПредоплатуИлиВыполнилисьДругиеУсловия--НеобходимоЗавеериштьЮридическоеСобытиеПродвинутьСделку
НеобходимоЗавеериштьЮридическоеСобытиеПродвинутьСделку--ПеревестиЮридическоеСобытивСтатусЗавершеноИсполнение
ПеревестиЮридическоеСобытивСтатусЗавершеноИсполнение--updateLegalExecutionComplete
updateLegalExecutionComplete--ЮридическоеСобытиеПредоставленоКПперешловСтатусЗавершеноИсполнение

ЮридическоеСобытиеПредоставленоКПперешловСтатусЗавершеноИсполнение .. LegalEvent2
LegalEvent2 .. ПредложенияПерешлиВСтадиюКоммерческоеПредложение
ПредложенияПерешлиВСтадиюКоммерческоеПредложение .. Order1
Order1 .. ДолжнаБытьЗакрытаЗадачаДанныеОКлиентеИАвто

ДолжнаБытьЗакрытаЗадачаДанныеОКлиентеИАвто--СоздатьЗадачу
СоздатьЗадачу--kafka_serviceLegalEventsEventsConsumer2
kafka_serviceLegalEventsEventsConsumer2--ЗадачаПриемкаТССоздана
ЮридическоеСобытиеПредоставленоКПперешловСтатусЗавершеноИсполнение-->kafka_serviceLegalEventsEventsConsumer2

ЗадачаПриемкаТССоздана .. Task2


@enduml