@startuml preparation_signing_documentts

title "Подготовка и подпись документов"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()


'yellow
Person('СПРК1', 'СПРК')
Person('СПРК2', 'СПРК')
Person('СПРК3', 'СПРК')

'blue
Command('ПозвонитьКлиенту', 'Позвонить клиенту')
Command('ПереходвЭкраншагПодготовкаДокументов', 'Переход в Экран/шаг "Подготовка документов"')
Command('РаспечататьНеобходимыеДокументы', 'Распечатать необходимые документы')
Command('ЗакрытьЗадачу', 'Закрыть задачу')
Command('ПоменятьСтатус', 'Поменять статус')


DomainEvent('КлиентОповещен', 'Клиент оповещен')
DomainEvent('КлиентПриеехал', 'Клиент приехал')
DomainEvent('ДокументыРаспечатаны', 'Документы распечатаны')
DomainEvent('ЮридическийДокументКЗНРаспечатан', 'Юридический документ "КЗН" распечатан')
DomainEvent('ЮридическийДокументГЗНРаспечатан', 'Юридический документ "ГЗН" распечатан')
DomainEvent('ЮридическийДокументАППВыполненныхРаботРаспечатан', 'Юридический документ "АПП выполненных работ" распечатан')
DomainEvent('ЮридическийДокументВЗНРаспечатан', 'Юридический документ "ВЗН" распечатан')
DomainEvent('ЮридическийДокументСЗНРаспечатан', 'Юридический документ "СЗН" распечатан')
DomainEvent('КлиентиСПРКподписалиЗаказнаряды', 'Клиент и СПРК подписали заказ-наряды')
DomainEvent('Документыподписаны', 'Документы подписаны')
DomainEvent('ЮридическийДокументСЗНподписанКлиентомиСПРК', 'Юридический документ "СЗН" подписан клиентом и СПРК')
DomainEvent('ЮридическийдокументВЗНподписанклиентомиСПРК', 'Юридический документ "ВЗН" подписан клиентом и СПРК')
DomainEvent('ЮридическийДокументГЗНподписанКлиентомиСПРК', 'Юридический документ "ГЗН" подписан клиентом и СПРК')
DomainEvent('ЮридическийДокументКЗНподписанКлиентомиСПРК', 'Юридический документ "КЗН" подписан клиентом и СПРК')


'pink
System('callPhone', 'callPhone')
System('pforms_getPDF', 'pforms_getPDF')
System('signLegalDocument', 'signLegalDocument')
System('uploadSignedLegalDocument', 'uploadSignedLegalDocument')

'fiolet
Policy('НеобходимоОповеститьКлиентаоГотовностиидождатьсяЕго', 'Необходимо оповестить клиента о готовности и дождаться его')
Policy('ДолжнаБытьЗакрытаЗадачаПодготовкаДокументов', 'Должна быть закрыта задача "Подготовка документов"')
Policy('ЗаказНарядыДолжныБытьПодписаны', 'Заказ-наряды должны быть подписаны')
Policy('УДокументаДолженБытьИзмененСтатус', 'У документа должен быть изменен статус')


'grenn
UserInterface('ТостШагПодготовкаДокументовРазблокирован', 'Тост "Шаг "Подготовка документов" разблокирован"')
UserInterface('ЭкранПодготовкаДокументов', 'Экран "Подготовка документов"')
UserInterface('ОкноНеобходимоПодтвердитьПодписаниеДокумента', 'Окно "Необходимо подтвердить подписание документа"')


Aggregate('LegalDocument7', 'Legal Document')
Aggregate('LegalDocument8', 'Legal Document')
Aggregate('LegalDocument9', 'Legal Document')
Aggregate('LegalDocument10', 'Legal Document')
Aggregate('LegalDocument11', 'Legal Document')
Aggregate('LegalDocument12', 'Legal Document')
Aggregate('LegalDocument13', 'Legal Document')
Aggregate('LegalDocument14', 'Legal Document')
Aggregate('LegalDocument15', 'Legal Document')


Container_Boundary(container, "") {
    System('kafka_serviceLegalDocumentsEventsConsumer', 'kafka_serviceLegalDocumentsEventsConsumer')
    DomainEvent('ЗакрытаЗадачаПодготовкаДокументов', 'Закрыта задача "Подготовка документов"')
    Aggregate('Task1', 'Task')
    DomainEvent('ЗадачаОплатаСоздана', 'Задача "Оплата" создана')
    Aggregate('Task2', 'Task')
}

Container_Boundary(container1,""){
    System('UICommand', 'UI Command')
    DomainEvent('НажатаКнопкаПерехода', 'Нажата кнопка перехода')
    Policy('ВыполняютсяПроверкиВыбранныхОпций', 'Выполняются проверки выбранных опций')
    Command('ВыполнитьПроверкииСоздатьДокумент', 'Выполнить проверки и создать документ')
    System('createLegalDocument', 'createLegalDocument')
    DomainEvent('ДокументыСозданы', 'Документы созданы')
    DomainEvent('ЮридическийДокументКЗНСоздан', 'Юридический документ "КЗН" создан')
    DomainEvent('ЮридическийДокументГЗНСоздан', 'Юридический документ "ГЗН" создан')
    DomainEvent('ЮридическийДокументВЗНСоздан', 'Юридический документ "ВЗН" создан')
    DomainEvent('ЮридическийДокументСЗНСоздан', 'Юридический документ "СЗН" создан')
    DomainEvent('ЮридическийДокументАППВыполненныхРаботСоздан', 'Юридический документ "АПП выполненных работ" создан')
    Aggregate('LegalDocument1', 'Legal Document')
    Aggregate('LegalDocument2', 'Legal Document')
    Aggregate('LegalDocument3', 'Legal Document')
    Aggregate('LegalDocument4', 'Legal Document')
    Aggregate('LegalDocument5', 'Legal Document')
    System('generatePdfForLegalDocument', 'generatePdfForLegalDocument')
    DomainEvent('ПФсгенерированы', 'ПФ сгенерированы')
    DomainEvent('УВсехДокументовИзмененстатусПолученаПФ', 'У всех документов изменен статус: "Получена ПФ"')
    Aggregate('LegalDocument6', 'Legal Document')
}



НеобходимоОповеститьКлиентаоГотовностиидождатьсяЕго--ПозвонитьКлиенту
ПозвонитьКлиенту--callPhone
callPhone--КлиентОповещен
КлиентОповещен--КлиентПриеехал
КлиентПриеехал--ТостШагПодготовкаДокументовРазблокирован
ТостШагПодготовкаДокументовРазблокирован--СПРК1
СПРК1--ПереходвЭкраншагПодготовкаДокументов
ПереходвЭкраншагПодготовкаДокументов--UICommand
UICommand--НажатаКнопкаПерехода
НажатаКнопкаПерехода--ВыполняютсяПроверкиВыбранныхОпций
ВыполняютсяПроверкиВыбранныхОпций--ВыполнитьПроверкииСоздатьДокумент
ВыполнитьПроверкииСоздатьДокумент--createLegalDocument
createLegalDocument--ДокументыСозданы
ДокументыСозданы--generatePdfForLegalDocument
generatePdfForLegalDocument--ПФсгенерированы
ПФсгенерированы--УВсехДокументовИзмененстатусПолученаПФ

УВсехДокументовИзмененстатусПолученаПФ .. LegalDocument6
LegalDocument6 .. ЭкранПодготовкаДокументов


ЭкранПодготовкаДокументов--СПРК2
СПРК2--РаспечататьНеобходимыеДокументы
РаспечататьНеобходимыеДокументы--pforms_getPDF
pforms_getPDF--ДокументыРаспечатаны
ДокументыРаспечатаны--ДолжнаБытьЗакрытаЗадачаПодготовкаДокументов
ДолжнаБытьЗакрытаЗадачаПодготовкаДокументов--ЗакрытьЗадачу
ЗакрытьЗадачу--kafka_serviceLegalDocumentsEventsConsumer
kafka_serviceLegalDocumentsEventsConsumer--ЗакрытаЗадачаПодготовкаДокументов

ЗакрытаЗадачаПодготовкаДокументов .. Task1
Task1 .. ЗадачаОплатаСоздана
ЗадачаОплатаСоздана .. Task2
Task2 .. ЗаказНарядыДолжныБытьПодписаны

ЗаказНарядыДолжныБытьПодписаны--КлиентиСПРКподписалиЗаказнаряды
КлиентиСПРКподписалиЗаказнаряды--УДокументаДолженБытьИзмененСтатус
УДокументаДолженБытьИзмененСтатус--ОкноНеобходимоПодтвердитьПодписаниеДокумента
ОкноНеобходимоПодтвердитьПодписаниеДокумента--СПРК3
СПРК3--ПоменятьСтатус

ПоменятьСтатус--signLegalDocument
ПоменятьСтатус--uploadSignedLegalDocument

uploadSignedLegalDocument--Документыподписаны
signLegalDocument--Документыподписаны



ЮридическийДокументКЗНСоздан .. LegalDocument1
ЮридическийДокументГЗНСоздан .. LegalDocument2
ЮридическийДокументВЗНСоздан .. LegalDocument3
LegalDocument4 .. ЮридическийДокументСЗНСоздан
LegalDocument5 .. ЮридическийДокументАППВыполненныхРаботСоздан


ЮридическийДокументКЗНСоздан--ДокументыСозданы 
ЮридическийДокументГЗНСоздан--ДокументыСозданы
ЮридическийДокументВЗНСоздан--ДокументыСозданы
ЮридическийДокументСЗНСоздан--ДокументыСозданы
ЮридическийДокументАППВыполненныхРаботСоздан--ДокументыСозданы

Lay_L(ЮридическийДокументКЗНСоздан,ДокументыСозданы)
Lay_L(ЮридическийДокументГЗНСоздан,ДокументыСозданы)
Lay_L(ЮридическийДокументВЗНСоздан,ДокументыСозданы)
Lay_R(ЮридическийДокументСЗНСоздан,ДокументыСозданы)
Lay_R(ЮридическийДокументАППВыполненныхРаботСоздан,ДокументыСозданы)


ЮридическийДокументКЗНРаспечатан .. LegalDocument7
ЮридическийДокументГЗНРаспечатан .. LegalDocument8
ЮридическийДокументАППВыполненныхРаботРаспечатан .. LegalDocument9
LegalDocument10 .. ЮридическийДокументВЗНРаспечатан
LegalDocument11 .. ЮридическийДокументСЗНРаспечатан

ЮридическийДокументКЗНРаспечатан--ДокументыРаспечатаны:includes
ЮридическийДокументГЗНРаспечатан--ДокументыРаспечатаны:includes
ЮридическийДокументАППВыполненныхРаботРаспечатан--ДокументыРаспечатаны:includes
ЮридическийДокументВЗНРаспечатан--ДокументыРаспечатаны:includes
ЮридическийДокументСЗНРаспечатан--ДокументыРаспечатаны:includes


Lay_L(ЮридическийДокументКЗНРаспечатан,ДокументыРаспечатаны)
Lay_L(ЮридическийДокументГЗНРаспечатан,ДокументыРаспечатаны)
Lay_L(ЮридическийДокументАППВыполненныхРаботРаспечатан,ДокументыРаспечатаны)
Lay_R(ЮридическийДокументВЗНРаспечатан,ДокументыРаспечатаны)
Lay_R(ЮридическийДокументСЗНРаспечатан,ДокументыРаспечатаны)


ЮридическийДокументСЗНподписанКлиентомиСПРК .. LegalDocument12
ЮридическийдокументВЗНподписанклиентомиСПРК .. LegalDocument13
ЮридическийДокументГЗНподписанКлиентомиСПРК .. LegalDocument14
ЮридическийДокументКЗНподписанКлиентомиСПРК .. LegalDocument15

ЮридическийДокументСЗНподписанКлиентомиСПРК--Документыподписаны:includes
ЮридическийдокументВЗНподписанклиентомиСПРК--Документыподписаны:includes
ЮридическийДокументГЗНподписанКлиентомиСПРК--Документыподписаны:includes
ЮридическийДокументКЗНподписанКлиентомиСПРК--Документыподписаны:includes

Lay_L(ЮридическийДокументСЗНподписанКлиентомиСПРК,Документыподписаны)
Lay_L(ЮридическийдокументВЗНподписанклиентомиСПРК,Документыподписаны)
Lay_L(ЮридическийДокументГЗНподписанКлиентомиСПРК,Документыподписаны)
Lay_L(ЮридическийДокументКЗНподписанКлиентомиСПРК,Документыподписаны)


@enduml
