@startuml regustartion for delivery

title "Запись клиента на выдачу"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

'yellow
Person('СПРК', 'СПРК')

'blue
Command('ЗаписатьНаВыдачу', 'Записать на выдачу')
Command('ПеревестиЮридическоеСобытиевСтатусЗавершеноИсполнение', 'Перевести  Юридическое событие в статус "Завершено исполнение"')
Command('СоздатьЗадачу', 'Создать задачу')


DomainEvent('ЗаписьВКалендареСоздана', 'Запись в календаре создана')
DomainEvent('ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусЗавершеноИсполнение','Юридическое событие "Заключёно предварительное соглашение" перешло в статус "Завершено исполнение"')
DomainEvent('ПредложенияПерешливСтадиюОбязательство','Предложения перешли в стадию "Обязательство"')
DomainEvent('АвтомбильпринятИготовкВыполнениюРабот','Автомбиль принят и готов к выполнению работ')
DomainEvent('ЗадачаРемонтТСоздана','Задача "Ремонт ТС" создана')

'pink
System('postCalendarSlot_v2', 'postCalendarSlot_v2')
System('updateLegalExecutionComplete', 'updateLegalExecutionComplete')
System('kafka_serviceNeedsEventsConsumer', 'kafka_serviceNeedsEventsConsumer')


'fiolet
Policy('НеобходимоЗавершитьЮридическоеСобытиеПродвинутьСделку', 'Необходимо завершить юридическое событие ( продвинуть сделку )')
Policy('ДолжнаБытьСозданаЗадачаРемонтТС', 'Должна быть создана задача "Ремонт ТС"')

'grenn
UserInterface('ЭкранШагЗаписьНаВыдачу', 'Экран/шаг "Запись на выдачу"')

Aggregate('Task', 'Task')
Aggregate('LegalEvent', 'Legal Event')
Aggregate('Order', 'Order')


ЭкранШагЗаписьНаВыдачу--СПРК
СПРК--ЗаписатьНаВыдачу
ЗаписатьНаВыдачу--postCalendarSlot_v2
postCalendarSlot_v2--ЗаписьВКалендареСоздана
ЗаписьВКалендареСоздана--НеобходимоЗавершитьЮридическоеСобытиеПродвинутьСделку

НеобходимоЗавершитьЮридическоеСобытиеПродвинутьСделку--ПеревестиЮридическоеСобытиевСтатусЗавершеноИсполнение
ПеревестиЮридическоеСобытиевСтатусЗавершеноИсполнение--updateLegalExecutionComplete
updateLegalExecutionComplete--ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусЗавершеноИсполнение

ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусЗавершеноИсполнение .. LegalEvent
LegalEvent .. ПредложенияПерешливСтадиюОбязательство
ПредложенияПерешливСтадиюОбязательство .. Order
Order .. АвтомбильпринятИготовкВыполнениюРабот

АвтомбильпринятИготовкВыполнениюРабот--ДолжнаБытьСозданаЗадачаРемонтТС
ДолжнаБытьСозданаЗадачаРемонтТС--СоздатьЗадачу
СоздатьЗадачу--kafka_serviceNeedsEventsConsumer
kafka_serviceNeedsEventsConsumer--ЗадачаРемонтТСоздана

ЗадачаРемонтТСоздана .. Task

ЮридическоеСобытиеЗаключёноПредварительноеСоглашениеПерешловСтатусЗавершеноИсполнение-->kafka_serviceNeedsEventsConsumer

@enduml