@startuml test3


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml

skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

Person('МастерКонсультант', 'Мастер консультант')
Person('МастерЦеха', 'Мастер цеха')

Command('ЗапрашиваетСписокРаботСНормированнымиЧасами', 'Запрашивает Список Работ С Нормированными Часами')
Command('УстанавливаетДлительностьРабот', 'Устанавливает Длительность Работ')
Command('ВыбираетЦехДляОтображения', 'Выбирает Цех Для Отображения')
Command('ВыбираетДатуДляРабот', 'Выбирает Дату Для Работ')
Command('ВыбираетМасштабОтображения', 'Выбирает Масштаб Отображения')
Command('ДобавляетНераспределеннуюЗадачуВКалендарь', 'Добавляет Нераспределенную Задачу В Календарь')

System('MDM', 'MDM')

DomainEvent('ДлительностьРаботУстановлена', 'Длительность Работ Установлена')
DomainEvent('СписокНераспределенныхЗадачОтображен', 'Список Нераспределенных Задач Отображен')
DomainEvent('СписокРаспределенныхЗадачОтображен', 'Список Распределенных Задач Отображен')
DomainEvent('СписокСвободныхСлотовОтображен', 'Список Свободных Слотов Отображен')
DomainEvent('ПостыВыбранногоЦехаОтображены', 'Посты Выбранного Цеха Отображены')
DomainEvent('ВыбранаДругаяДата', 'Выбрана Другая Дата')
DomainEvent('ИзмененШаг30минЧас', 'Изменен Шаг 30 мин/час')

DomainEvent('ДлительностьРаботУстановлена', 'Длительность Работ Установлена')

Policy('МеханикРаспределенНаПост', 'Механик Распределен На Пост')
Policy('НаПостуНетМеханика', 'На Посту Нет Механика')
Policy('ПланируемоеВремяМеньшеРеальногоВремени', 'Планируемое Время Меньше Реального Времени')



МастерКонсультант -- ЗапрашиваетСписокРаботСНормированнымиЧасами
ЗапрашиваетСписокРаботСНормированнымиЧасами -- MDM
MDM -- УстанавливаетДлительностьРабот
УстанавливаетДлительностьРабот -- ДлительностьРаботУстановлена
ДлительностьРаботУстановлена -- ИнтерфейсКалендарь
ИнтерфейсКалендарь -- МастерЦеха
МастерЦеха -- ВыбираетЦехДляОтображения
ВыбираетЦехДляОтображения -- ПостыВыбранногоЦехаОтображены
ПостыВыбранногоЦехаОтображены -- ВыбираетДатуДляРабот
ВыбираетДатуДляРабот -- ВыбранаДругаяДата
ВыбранаДругаяДата -- ВыбираетМасштабОтображения
ВыбираетМасштабОтображения -- ИзмененШаг30минЧас
ИзмененШаг30минЧас -- ДобавляетНераспределеннуюЗадачуВКалендарь
ДобавляетНераспределеннуюЗадачуВКалендарь -- МеханикРаспределенНаПост
ДобавляетНераспределеннуюЗадачуВКалендарь -- НаПостуНетМеханика


@enduml