@startuml work_spareparts

title "Наполнение работ и запчастей в ПЗН для Клиента"


' loads the package bootstrap
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml


skinparam svgLinkTarget _blank

LAYOUT_LEFT_RIGHT()

'yellow
Person('СПРК', 'СПРК')


'blue
Command('НайтиРаботыИЗапчасти', 'Найти работы и запчасти')
Command('ДобавитьРаботуИЗапчасть', 'Добавить работу и запчасть')
Command('ВыполнитьРезервЗапчастей', 'Выполнить резерв запчастей')



DomainEvent('НайденыРаботыИЗапчасти', 'Найдены работы и запчасти')
DomainEvent('СозданоПредложениеЗапчасти','Создано предложение "Запчасти"')
DomainEvent('СозданоПредложениеРабота','Создано предложение "Работа"')
DomainEvent('СущностьЗНВАСРольфСоздана','Сущность "ЗН" в АС Рольф создана')

'pink
System('bff_getWorksAndDetails', 'cbff_getWorksAndDetails')
System('addWorksAndDetails_v3', 'addWorksAndDetails_v3')
System('inegration_int', 'inegration_int')


'fiolet
Policy('НайднныеРаботыИЗЧДолжныБытьВПЗН', 'Найденные работы и ЗЧ должны быть добавленны в ПЗН')
Policy('ИнтеграцияСАСРольф', 'Интеграция с АС Рольф')  

'grenn
UserInterface('ЭкранРаботыИЗапчасти1', 'Экран "Работы и запчасти"')
UserInterface('ЭкранРаботыИЗапчасти2', 'Экран "Работы и запчасти"')

Aggregate('Order1', 'Order')
Aggregate('Order2', 'Order')



ЭкранРаботыИЗапчасти1--СПРК
СПРК--НайтиРаботыИЗапчасти
НайтиРаботыИЗапчасти--bff_getWorksAndDetails
bff_getWorksAndDetails--НайденыРаботыИЗапчасти
НайденыРаботыИЗапчасти--НайднныеРаботыИЗЧДолжныБытьВПЗН
НайднныеРаботыИЗЧДолжныБытьВПЗН--ДобавитьРаботуИЗапчасть
ДобавитьРаботуИЗапчасть--addWorksAndDetails_v3
addWorksAndDetails_v3--СозданоПредложениеЗапчасти
addWorksAndDetails_v3--СозданоПредложениеРабота

СозданоПредложениеЗапчасти .. Order1
СозданоПредложениеРабота .. Order2
Order1 .. ИнтеграцияСАСРольф
Order2 .. ИнтеграцияСАСРольф

ИнтеграцияСАСРольф--ВыполнитьРезервЗапчастей
ВыполнитьРезервЗапчастей--inegration_int
inegration_int--СущностьЗНВАСРольфСоздана
СущностьЗНВАСРольфСоздана--ЭкранРаботыИЗапчасти2

@enduml


