---
title: Выкуп АСП
weight: 4
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_01_01_01_03_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_01_01_01_03_img/

= Выкуп АСП

{empty} +

. *WMS-1. Приемка автомобля с пробегом*
+
====
* Ключ #Уточнить и описать серверную функциональность участвующую в этой активности! (Получение ключа от владельца автомобиля, фиксация этого события и т.д.)#
* Колеса БУ #Уточнить и описать серверную функциональность участвующую в этой активности! (Получение колес от владельца автомобиля, фиксация этого события и т.д.)# icon:minus-circle[role=red]
* Предпродажная подготовка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Сервис #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Фото #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Мойка, химчистка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Заказ перевозчика #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Внутреннее перемещение #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Внешнее перемещение #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Чек-лист приемки АСП #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *АСП - WMS*: запрос на создание задачи по приемке после выкупа
* Синхронизация стока *Flora* и *WMS авто*
====


{empty} +

*BP-3. БП Модуль - Управление выкупом АСП + БУ Шин  для Физ. лиц и Юр. лиц*

. Проверка истории обращений компании по объявлениям с классифайдов icon:minus-circle[role=red]
. Осмотр АСП icon:check-circle[role=green]
* Отправка и получение отчета из Автотеки icon:check-circle[role=green]
* Проведение осмотра с помощью CarInspect icon:check-circle[role=green]
* Выгрузка данных из приложения для осмотра CarInspect icon:check-circle[role=green]
* Создание карточки товара на выкупаемые колеса icon:check-circle[role=green] 
* Формирование/редактирование акта осмотра icon:check-circle[role=green]
. Формирование цены выкупа icon:check-circle[role=green]
* Вывод аналитической информации по выкупаемой модели: анализ рынка, анализ стока, история продаж, наличие резины и второго комплекта ключей, сервисная книжка, секретки icon:check-circle[role=green]
* Формирование и согласование цены выкупа icon:check-circle[role=green]
* Прикрепление сканов документов icon:check-circle[role=green]
* Проверка СОПД, подписание с клиентом и загрузка в систему icon:check-circle[role=green]
* Отправка запроса на проверку службой безопасности icon:check-circle[role=green]
* Экраны для СБ icon:check-circle[role=green]
* Получение отчета от СБ icon:check-circle[role=green]
* Продажа услуг снятия АСП с гос. регистрации icon:minus-circle[role=red]
. Выкуп по комиссии icon:minus-circle[role=red]
* Формирование и согласование цены выкупа icon:minus-circle[role=red]
* Формирование документов для продажи: договор поручение icon:minus-circle[role=red]
* Заполнение описания автомобиля icon:minus-circle[role=red]
* Формирование номера ключа в ключнице icon:minus-circle[role=red]
* Формирование чеклиста на передачу материальных ценностей icon:minus-circle[role=red]
* Проверка передаваемых документов по чеклисту icon:minus-circle[role=red]
* Отметка в системе о передачи документов по сделке и ключей на хранение icon:minus-circle[role=red]
. Рольф Meeting Point icon:minus-circle[role=red]
* Загрузка фотографий АСП icon:minus-circle[role=red]
* Добавление технической информации по асп icon:minus-circle[role=red]
* Получение статуса продажи асп в качестве агента продажи без физического присутствия асп icon:minus-circle[role=red]
* Редактирование и согласование цены продажи icon:minus-circle[role=red]
. Диагностика icon:check-circle[role=green]
* Запрос в сервисе слота на диагностику icon:minus-circle[role=red]
* Создание задачи для техника сервиса icon:check-circle[role=green]
* Получение ЭКД icon:check-circle[role=green]
* Приём а/м из диагностики задача для техника сервиса icon:check-circle[role=green]
. Формирование финального предложения icon:check-circle[role=green]
* Формирование и согласование цены выкупа icon:check-circle[role=green]
* Изменение и подписание акта с клиентом и загрузка в систему icon:check-circle[role=green]
. Оформление документов icon:check-circle[role=green]
* Формирование и распечатка ДКП и АПП icon:check-circle[role=green]
* Выгрузка АСП на сайт (через обратную интеграцию с фишблю icon:check-circle[role=green]
* смена типа авто при успешном выкупе с "Клиентский" на "На продажу"  icon:check-circle[role=green]
* передача новой единицы (авто) в сток фишблю icon:check-circle[role=green]
. Оплата АСП клиенту icon:check-circle[role=green]
* Формирование направление на выплату ДС через оперкассу icon:check-circle[role=green]
* Отчет о завершении выплаты денежных средств клиенту icon:minus-circle[role=red]
* Выплаты через Альфа банк icon:check-circle[role=green]
. Передача материальных ценностей icon:check-circle[role=green]
* Формирование и распечатка бирок на резину icon:minus-circle[role=red]
* Передача данных по шинам в АС РОЛЬФ icon:check-circle[role=green]
* Формирование списка задач на предпродажную подготовку icon:check-circle[role=green]
* Согласование списка задач на предпродажную подготовку icon:minus-circle[role=red]
* Заполнение описание АСП от специалиста по выкупу (P-16)icon:check-circle[role=green]
* Формирование номера ключа в ключнице icon:minus-circle[role=red]
* Формирование чеклиста на получение материальных ценностей от клиента icon:check-circle[role=green]
* Отметка в системе о передаче документов по сделке и ключей на хранение icon:check-circle[role=green]
. Трейд-ин icon:minus-circle[role=red]