[plantuml%interactive,"tasks_and_events",format=svg,align=center,width=50%]
.Tasks and events - Задачи, события и оповещения
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")
System(tasks_and_events, "Tasks and events", "Задачи, события и оповещения")
System(tasks, "Tasks", "Задачи", $link="/05_c4_workflow/01_core/05_tasks_and_events/01_tasks/")
System(events, "Events", "События", $link="/05_c4_workflow/01_core/05_tasks_and_events/02_events/")

Rel_D(core, tasks_and_events, "")
Rel_D(tasks_and_events, tasks, "")
Rel_D(tasks_and_events, events, "")

@enduml
----
