[plantuml%interactive,"needs_and_orders",format=svg,align=center,width=100%]
.Needs and orders - Обращения, потребности, предложения
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'left to right direction

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent

<style>
System {
    MinimumWidth 300
    MinimumHeight 150
}
</style>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()
'LAYOUT_LANDSCAPE()

System(core, "Core", "Общий функционал", $link="/05_c4/01_core/")

System(needs_and_orders, "Needs and orders", "Обращения, потребности, предложения")

System(requests, "Requests", "Запросы", $link="/05_c4/01_core/03_needs_and_orders/01_requests/")
System(needs, "Needs", "Потребности", $link="/05_c4/01_core/03_needs_and_orders/02_needs/")
System(carts, "Carts", "Корзины", $link="/05_c4/01_core/03_needs_and_orders/03_carts/")
System(orders, "Orders", "Заказы", $link="/05_c4/01_core/03_needs_and_orders/04_orders/")
System(legal_events, "Legal events", "Юридические события", $link="/05_c4/01_core/03_needs_and_orders/05_legal_events/")
System(legal_documents, "Legal documents", "Юридические документы", $link="/05_c4/01_core/03_needs_and_orders/06_legal_documents/")

Rel_D(core, needs_and_orders, "")

Rel_D(needs_and_orders, requests, "")
Rel_D(needs_and_orders, needs, "")
Rel_D(needs_and_orders, carts, "")
Rel_D(needs_and_orders, orders, "")
Rel_D(needs_and_orders, legal_events, "")
Rel_D(needs_and_orders, legal_documents, "")

@enduml
----

