---
title: "АРМ сотрудника"
slug: "01_apm_employee"
weight: 3
---

:toc: auto
:toc-title: Содержание
:toclevels: 5
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_01_01_01_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_01_01_01_img/

= АРМ сотрудника

{empty} +

====
IMPORTANT: Знаком icon:check-circle[role=green] отмечены активности которые *ВОЙДУТ* в MVP на МАРТ 2023 года!!! +
Знаком icon:minus-circle[role=red] отмечены активности которые *[red]#НЕ# ВОЙДУТ в* MVP на МАРТ 2023 года!!!
====

== Задачи решаемые модулем CRM-1 footnote:CRM-1[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*CRM-1. Управление коммуникациями с клиентами*#.] по управлению коммуникациями с клиентами

****
[.red.background]
====
. Визуализация истории всех коммуникаций с клиентами по всем каналам с возможностью сортировки и фильтрации в разрезе канала, типа коммуникации или клиента. (источником данных может быть CRM-6) icon:minus-circle[role=red]
. Создание новой массовой коммуникации по заданному каналу/лам, по выбранному сегменту, по заданному шаблону и с указанием даты запуска. icon:minus-circle[role=red]
. Отслеживание статуса коммуникации и анализ её эффективности. ( анализ с помощью  CRM-9) icon:minus-circle[role=red]
====
****
****
NOTE: Персональные коммуникации с клиентами будут происходить через карточку клиента +
Рассматриваем вариант вендора: *MindBox*
****

== Задачи решаемые модулем CRM-2 footnote:CRM-2[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*CRM-2. Управление лояльностью клиентов. Включая ПЛ.*#.] по управлению лояльностью клиентов

****
Админка функционала Программы лояльности:
[.red.background]
====
. Типы карт icon:minus-circle[role=red]
. Условия получения карт icon:minus-circle[role=red]
. Списки участников ПЛ icon:minus-circle[role=red]
====
****
****
NOTE: Рассматриваем вариант вендора: *Loymax или MindBox*
****

== Задачи решаемые модулем CRM-3 footnote:CRM-3[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*CRM-3. Управление маркетинговой активностью: акции и скидки.*#.] по управлению лояльностью клиентов

****
[.green.background]
====
. Сущность "Скидка" в системе, влияющая на стоимость товара icon:check-circle[role=green]
. Назначение типа скидки на товар или группу товаров icon:check-circle[role=green]
====
[.red.background]
====
. Визуализация всех активных и архивных акций компании, внутренних и импортерских, с возможностью сортировки и фильтрации в разрезе источника, статуса или типа акции. icon:minus-circle[role=red]
. Создание новой акции по выбранному: бренду, бизнес юниту, локации, модели авто, сегменту клиентов, сегменту автомобилей. С возможностью создавать и сохранять шаблоны, указывать фото и ссылки, необходимость публикации акции на сайтах и в МП и назначать дату запуска. icon:minus-circle[role=red]
. Отслеживание статуса акции и анализ её эффективности. icon:minus-circle[role=red]
====
****

== Задачи решаемые модулем CRM-4 footnote:CRM-4[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*CRM-4. Рабочее место сотрудника: задачи, график. Линейный перс. и руководители*#.] по управлению задачами сотрудника и графиком его загруженности

****
[.green.background]
====
. Отображение всех активных и архивных задач/обращений, потребностей, клиентов, авто с которыми работает сотрудник с возможностью поиска и фильтрации icon:check-circle[role=green]
. Отображение  задач/обращений, потребностей, клиентов, авто с которыми работают починенные (способ соотношения рук-подчиненный уточняется) icon:check-circle[role=green]
. Отображение графика работ icon:check-circle[role=green]
. Функционал включения и завершения рабочего дня icon:check-circle[role=green] с выбором ДЦ будет после MVP
. Уведомления о новых задачах icon:check-circle[role=green]
====
[.red.background]
====
. Возможность вывода виджетов необходимых для работы (не MVP) icon:minus-circle[role=red]
. Возможность коммуникации с коллегами (link:/02_architecture/02_backend/15_communicationservice/#SERV-5[*SERV-5*, window=_blank]) icon:minus-circle[role=red] и с клиентами (link:/02_architecture/01_frontend/01_onerolf/04_clientsui/#ID-1[*ID-1*, window=_blank]) (некое отдельное решение закрывающее вопрос коммуникаций по выбранному каналу) icon:minus-circle[role=red]
. Получение важных уведомлений и новостей, влияющих на работу (срочные уведомления) icon:minus-circle[role=red]
. Стандарты, скрипты и чек листы (база знаний) icon:minus-circle[role=red]
. Основные показатели KPI icon:minus-circle[role=red]
====
*Интеграции внешние и внутренние*
[.green.background]
====
* Контакты и задачи в оракле icon:check-circle[role=green]
* АС Рольф icon:check-circle[role=green]
* Web Сервис icon:check-circle[role=green]
====
****