---
title: АРМ сотрудника
weight: 3
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_01_01_01_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_01_01_01_img/

= АРМ сотрудника

{empty} +

*CRM-1. Управление коммуникациями с клиентами*

. Визуализация истории всех коммуникаций с клиентами по всем каналам с возможностью сортировки и фильтрации в разрезе канала, типа коммуникации или клиента. (источником данных может быть CRM-6) icon:minus-circle[role=red]
. Создание новой массовой коммуникации по заданному каналу/лам, по выбранному сегменту, по заданному шаблону и с указанием даты запуска. icon:minus-circle[role=red]
. Отслеживание статуса коммуникации и анализ её эффективности. ( анализ с помощью  CRM-9) icon:minus-circle[role=red]

_*Персональные коммуникации с клиентами будут происходить через карточку клиента*_

_*Рассматриваем вариант вендора: MindBox*_

*CRM-2. Управление лояльностью клиентов. Включая ПЛ.*

Админка функционала Программы лояльности:

. Типы карт icon:minus-circle[role=red]
. Условия получения карт icon:minus-circle[role=red]
. Списки участников ПЛ icon:minus-circle[role=red]

_*Рассматриваем вариант вендора: Loymax или MindBox*_

*CRM-3. Управление маркетинговой активностью: акции и скидки.*

* Визуализация всех активных и архивных акций компании, внутренних и импортерских, с возможностью сортировки и фильтрации в разрезе источника, статуса или типа акции. icon:minus-circle[role=red]
* Создание новой акции по выбранному: бренду, бизнес юниту, локации, модели авто, сегменту клиентов, сегменту автомобилей. С возможностью создавать и сохранять шаблоны, указывать фото и ссылки, необходимость публикации акции на сайтах и в МП и назначать дату запуска.icon:minus-circle[role=red]
* Отслеживание статуса акции и анализ её эффективности. icon:minus-circle[role=red]
* Сущность "Скидка" в системе, влияющая на стоимость товара icon:check-circle[role=green]
* Назначение типа скидки на товар или группу товаров icon:check-circle[role=green]

*CRM-4. Рабочее место сотрудника: задачи, график. Линейный перс. и руководители*

* Отображение всех активных и архивных задач/обращений, потребностей, клиентов, авто с которыми работает сотрудник с возможностью поиска и фильтрации icon:check-circle[role=green]
* Отображение  задач/обращений, потребностей, клиентов, авто с которыми работают починенные (способ соотношения рук-подчиненный уточняется) icon:check-circle[role=green]
* Отображение графика работ icon:check-circle[role=green]
* Функционал включения и завершения рабочего дня  icon:check-circle[role=green] с выбором ДЦ будет после MVP
* Уведомления о новых задачах icon:check-circle[role=green]
* Возможность вывода виджетов необходимых для работы (не MVP)icon:minus-circle[role=red]
* Возможность коммуникации с коллегами (*SERV-5*) icon:minus-circle[role=red] и с клиентами (*ID-1*) (некое отдельное решение закрывающее вопрос коммуникаций по выбранному каналу)icon:minus-circle[role=red]
* Получение важных уведомлений и новостей, влияющих на работу (срочные уведомления)icon:minus-circle[role=red]
* Стандарты, скрипты и чек листы (база знаний) icon:minus-circle[role=red]
* Основные показатели KPI  icon:minus-circle[role=red]

*Интеграции внешние и внутренние*

* Контакты и задачи в оракле icon:check-circle[role=green]
* АС Рольф icon:check-circle[role=green]
* Web Сервис icon:check-circle[role=green]