---
title: АРМ руководителя
weight: 4
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_01_01_02_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_01_01_02_img/

= АРМ руководителя

{empty} +

*CRM-4. Рабочее место сотрудника: задачи, график. Линейный перс. и руководители*

* Отображение всех активных и архивных задач/обращений, потребностей, клиентов, авто с которыми работает сотрудник с возможностью поиска и фильтрации icon:check-circle[role=green]
* Отображение задач/обращений, потребностей, клиентов, авто с которыми работают починенные (способ соотношения рук-подчиненный уточняется) icon:check-circle[role=green]
* Отображение графика работ icon:check-circle[role=green]
* Функционал включения и завершения рабочего дня  icon:check-circle[role=green] с выбором ДЦ будет после MVP
* Уведомления о новых задачах icon:check-circle[role=green]
* Возможность вывода виджетов необходимых для работы (не MVP)icon:minus-circle[role=red]
* Возможность коммуникации с коллегами (*SERV-5*) icon:minus-circle[role=red] и с клиентами (*ID-1*) (некое отдельное решение закрывающее вопрос коммуникаций по выбранному каналу)icon:minus-circle[role=red]
* Получение важных уведомлений и новостей, влияющих на работу (срочные уведомления)icon:minus-circle[role=red]
* Стандарты, скрипты и чек листы (база знаний) icon:minus-circle[role=red]
* Основные показатели KPI icon:minus-circle[role=red]

*Интеграции внешние и внутренние*

* Контакты и задачи в оракле icon:check-circle[role=green]
* АС Рольф icon:check-circle[role=green]
* Web Сервис icon:check-circle[role=green]

{empty} +

*CRM-5. Панель руководителя: сотрудники, эффективность, планирование.*

* Формирование целевой модели и допустимых отклонений для дальнейшего сравнения её с фактической моделью работы и анализа эффективности. icon:minus-circle[role=red]
* Планирование загрузки работы сотрудника/отдела/локации. icon:minus-circle[role=red]
* Список подчиненных с визуализацией их загрузки и эффективности icon:minus-circle[role=red]