[plantuml%interactive,"core",format=svg,align=center,width=75%]
.Core - общий функционал
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

left to right direction

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent

<style>
System {
    MinimumWidth 300
    MinimumHeight 150
}
</style>

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()
'LAYOUT_LANDSCAPE()

System(flora, "Flora", "Система Flora", $link="/05_c4/")

System(core, "Core", "Общий функционал")
'Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")

System(coreapp, "Coreapp", "Комментарии, датагриды", $link="/05_c4/01_core/01_coreapp/")
System(payments, "Payments", "Платежи, чеки", $link="/05_c4/01_core/02_payments/")
System(needs_and_orders, "Needs and orders", "Обращения, потребности, предложения", $link="/05_c4/01_core/03_needs_and_orders/")
System(communications, "Communications", "Коммуникации", $link="/")
System(tasks_and_events, "Tasks and events", "Задачи, события и оповещения", $link="/")
System(rolfid, "Rolfid", "Сотрудники, пользователи, ДЦ", $link="/")
System(clientid, "Clientid", "Клиенты (физлица и организации)", $link="/")
System(carid, "Carid", "Транспортные средства", $link="/")
System(external_integrations, "External integrations", "Внешние интеграции", $link="/")
System(internal_integrations, "Internal integrations", "Внутренние интеграции", $link="/")
System(printservice, "Print service", "Печатные формы", $link="/")
System(pfanalize, "Pfanalize", "Сервисные услуги", $link="/")

Rel_R(flora, core, "")

Rel_D(core, coreapp, "")
Rel_D(core, payments, "")
Rel_D(core, needs_and_orders, "")
Rel_D(core, communications, "")
Rel_D(core, tasks_and_events, "")
Rel_D(core, rolfid, "")
Rel_U(core, clientid, "")
Rel_U(core, carid, "")
Rel_U(core, external_integrations, "")
Rel_U(core, internal_integrations, "")
Rel_U(core, printservice, "")
Rel_U(core, pfanalize, "")

@enduml
----

