[plantuml%interactive,"core",format=svg,align=center,width=75%]
.Core - общий функционал
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
'skinparam linetype polyline
skinparam minClassWidth 200

LAYOUT_LEFT_RIGHT()

System(flora, "Flora", "Система Flora", $link="/05_c4/")

System(core, "Core", "Общий функционал")
'Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")

System(coreapp, "Coreapp", "Комментарии, датагриды", $link="/05_c4/01_core/01_coreapp/")
System(payments, "Payments", "Платежи, чеки", $link="/05_c4/01_core/02_payments/")
System(needs_and_orders, "Needs and orders", "Обращения, потребности, предложения", $link="/05_c4/01_core/03_needs_and_orders/")
System(communications, "Communications", "Коммуникации", $link="/05_c4/01_core/04_communications/")
System(tasks_and_events, "Tasks and events", "Задачи, события и оповещения", $link="/05_c4/01_core/05_tasks_and_events/")
System(rolfid, "Rolfid", "Сотрудники, пользователи, ДЦ", $link="/05_c4/01_core/06_rolfid/")
System(clientid, "Clientid", "Клиенты (физлица и организации)", $link="/05_c4/01_core/07_clientid/")
System(carid, "Carid", "Транспортные средства", $link="/05_c4/01_core/08_carid/")
System(external_integrations, "External integrations", "Внешние интеграции", $link="/05_c4/01_core/09_external_integrations/")
System(internal_integrations, "Internal integrations", "Внутренние интеграции", $link="/05_c4/01_core/10_internal_integrations/")
System(printservice, "Print service", "Печатные формы", $link="/05_c4/01_core/11_printservice/")
System(pfanalize, "Print Form Aanalyze", "Сервисные услуги", $link="/05_c4/01_core/12_pfanalyze/")

Rel_R(flora, core, "")

Rel_D(core, coreapp, "")
Rel_D(core, payments, "")
Rel_D(core, needs_and_orders, "")
Rel_D(core, communications, "")
Rel_D(core, tasks_and_events, "")
Rel_D(core, rolfid, "")
Rel_U(core, clientid, "")
Rel_U(core, carid, "")
Rel_U(core, external_integrations, "")
Rel_U(core, internal_integrations, "")
Rel_U(core, printservice, "")
Rel_U(core, pfanalize, "")

@enduml
----

