[plantuml%interactive,"internal_integrations",format=svg,align=center,width=100%]
.Internal integrations - Внутренние интеграции
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_LEFT_RIGHT()

System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")

System(internal_integrations, "External integration", "Внешние интеграции")

System(oracle, "Oracle", "Oracle", $link="/05_c4_workflow/01_core/10_internal_integrations/01_oracle/")
System(centrifugo, "Centrifugo", "Centrifugo", $link="/05_c4_workflow/01_core/10_internal_integrations/02_centrifugo/")
System(smtp, "SMTP", "SMTP", $link="/05_c4_workflow/01_core/10_internal_integrations/03_smtp/")
System(asterisk, "Asterisk", "Asterisk", $link="/05_c4_workflow/01_core/10_internal_integrations/04_asterisk/")
System(mdm, "MDM", "MDM", $link="/05_c4_workflow/01_core/10_internal_integrations/05_mdm/")
System(wms, "WMS", "WMS", $link="/05_c4_workflow/01_core/10_internal_integrations/06_wms/")
System(saphr, "SAP HR", "SAP HR", $link="/05_c4_workflow/01_core/10_internal_integrations/07_saphr/")
System(keycloak, "Keycloak", "Keycloak", $link="/05_c4_workflow/01_core/10_internal_integrations/08_keycloak/")

Rel_R(core, internal_integrations, "")

Rel_D(internal_integrations, oracle, "")
Rel_D(internal_integrations, centrifugo, "")
Rel_D(internal_integrations, smtp, "")
Rel_U(internal_integrations, asterisk, "")
Rel_U(internal_integrations, mdm, "")
Rel_U(internal_integrations, wms, "")
Rel_U(internal_integrations, saphr, "")
Rel_U(internal_integrations, keycloak, "")

@enduml
----

