[plantuml%interactive,"f_and_i",format=svg,align=center,width=75%]
.F&I - Страхование и финансовые продукты
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(experience, "Experience", "Прикладные методы", $link="/05_c4_workflow/02_experience/")

System(f_and_i, "F&I", "Страхование и финансовые продукты")
System(f_and_i_node, "F&I", "Страхование и финансовые продукты", $link="/05_c4_workflow/02_experience/01_f_and_i/01_f_and_i_node/")
System(insurance, "Insurance", "Страхование", $link="/05_c4_workflow/02_experience/01_f_and_i/02_insurance/")
System(credit, "Credit", "Кредитование", $link="/05_c4_workflow/02_experience/01_f_and_i/03_credit/")

Rel_D(experience, f_and_i, "")
Rel_D(f_and_i, f_and_i_node, "")
Rel_D(f_and_i, insurance, "")
Rel_D(f_and_i, credit, "")

@enduml
----
