---
title: WMS - Система управления складом (Frontend)
weight: 4
---

{empty} +

*WMS-система управления складом* (Warehouse Management System) – система, предназначенная для автоматизации управления процессами склада и работы складского комплекса. +
Система будет решать следующие задачи:

{empty} +

****
. Приемка автомобля с пробегом
+
====
.. Ключ +
.. Колеса БУ (minus) +
.. Предпродажная подготовка +
.. Сервис (minus) +
.. Фото +
.. Мойка, химчистка +
.. Заказ перевозчика (minus) +
.. Внутреннее перемещение +
.. Внешнее перемещение +
.. чек-лист приемки АСП (minus)
====
+
. Приемка нового автомобиля
. Выдача нового автомобиля
. Выдача автомобиля с пробегом
. Аудит
. Рекомендательная система по выбору парковки
. TMS Запчасти
****

/**/
WMS-1. Приемка АСП
WMS-2. Приемка НА
WMS-3. Выдача НА
WMS-4. Выдача АСП
WMS-5. Аудит
WMS-6. Рекомендательная система по выбору парковки
WMS TMS Запчасти


WMS-1. Приемка АСП
    Ключ
    Колеса БУ (minus)
    Предпродажная подготовка
    Сервис (minus)
    Фото
    Мойка, химчистка
    Заказ перевозчика (minus) 
    Внутреннее перемещение
    Внешнее перемещение
    чек-лист приемки АСП (minus)

    (АСП - WMS: запрос на создание задачи по приемке после выкупа
    синхронизация стока Flora и WMS авто)

WMS-2. Приемка НА

    Внесение логистом НА в систему
    Заказ перевозчика✋, внесение данных о перевозке в систему
    Приемка в ДЦ Хранения
    Приемка в ДЦ Продажи
    Чек-лист повреждений по форме импортера (minus)
    Чек-лист на комплектность (minus)
    Запрос импортеру (minus)
    Перемещение на место хранения
    Чек-лист внешнего перемещения (minus)
    Получение/сдача ключа
    Предпродажная подготовка
    Установка допов (minus)
    Сервис (minus)
    Интеграция с перевозчиками (minus)
    Интеграция с системами импортеров (minus)
    Электронная ключная (minus)

WMS-3. Выдача НА
    Ключ
    Электронная ключная (minus)
    мойка
    химчистка
    Внутреннее перемещени
    Подменки (minus)
    Тест-драйв (minus)

    (НА - WMS: запрос на создание задачи по выдаче после подписания доков
    WMS - НА: передача статуса “машина готова к выдаче“, чтобы ПК принял, подтвердил и отдал машину клиенту)

WMS-4. Выдача АСП
    Ключ
    Электронная ключная (minus)
    мойка
    химчистка
    Внутреннее перемещение

    (АСП - WMS: запрос на создание задачи по выдаче после подписания доков
    WMS - АСП: передача статуса “машина готова к выдаче“, чтобы ПК принял, подтвердил и отдал машину клиенту)

WMS-5. Аудит
    Создание/изменение/удаление задач на разовый аудит
    Создание/изменение/удаление задач на регулярный аудит

WMS-6. Рекомендательная система по выбору парковки
    Создание/изменение/удаление правил рекомендательной системы

WMS TMS Запчасти
    приемка товарных единиц на склад
    размещение товарных единиц на местах хранения
    оптимизация размещения товарных единиц
    сборка заказов 
    упаковка заказов перед отгрузкой
    отгрузка заказов