---
title: MDM - Мастер данные
weight: 5
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:table-caption: Таблица
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_01_04_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_01_04_img/

{empty} +

====
NOTE: #Данная статья описывает функционал *MDM* относящийся к *Frontend*-у.#
====

{empty} +

****
Системы *MDM* (**M**aster **D**ata **M**anagement - управление мастер-данными) - это решения, предназначенные для управления *нормативно-справочной информацией* (*НСИ*). Целью внедрения систем *MDM* является обеспечение единства представления массивов *НСИ* во всех информационных системах и решение проблем несоответствия, несопоставимости и дублирования данных.
****

{empty} +

****
*MDM* решает следующие задачи:
====
. Обеспечение консолидации данных из различных систем
. Централизованное хранение нормативно-справочной информации
. Поддержание достоверной, актуальной и непротиворечивой информации
. Контроль за целостностью и согласованностью данных
. Обеспечение единых процессов ведения нормативно-справочной информации
====
Ключевые возможности *MDM* систем:
====
. Поддержка множества интеграционных механизмов со сторонними информационными системами
. Поддержка механизмов контроля качества и нормализации данных
. Импорт и экспорт данных с поддержкой распространённых форматов
. Поддержка ролевого доступа к данным
. Поддержка расширяемых моделей данных
====
****

====
IMPORTANT: Знаком icon:check-circle[role=green] отмечены активности которые *ВОЙДУТ* в MVP на МАРТ 2023 года!!! +
Знаком icon:minus-circle[role=red] отмечены активности которые *[red]#НЕ# ВОЙДУТ в* MVP на МАРТ 2023 года!!!
====

****
*MDM-1,2,3,4.* Создание/изменение/удаление справочной информации по *автомобилям, запчастям, опциям, работам.*
[.green.background]
====
. Экспорт (через файл *CSV*) icon:check-circle[role=green]
. Импорт (через файл *CSV*) icon:check-circle[role=green]
. Ручная загрузка (занесение данных через интерфейс) icon:check-circle[role=green]
====
[.red.background]
====
. Интеграция с *auto.ru* icon:minus-circle[role=red]
. Дедубликация icon:minus-circle[role=red]
====
****

****
*MDM-5. Процессы согласования*
[.green.background]
====
* Создание/изменение удаление процессов согласования внутри *MDM* icon:check-circle[role=green]
====
****