[plantuml%interactive,"pforms_tags",format=svg,align=center,width=30%]
.Print forms tags - Тэги печатных форм
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(printservice, "Print forms", "Сервис печатных форм", $link="/05_c4_workflow/01_core/11_printservice/")
System(pforms_tags, "Print forms tags", "Тэги печатных форм")

Rel_U(pforms_tags, printservice, "")

@enduml
----
