[plantuml%interactive,"external_integrations",format=svg,align=center,width=100%]
.External integrations - Внешние интеграции
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_LEFT_RIGHT()

System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")

System(external_integrations, "External integration", "Внешние интеграции")

System(elt, "Elt", "Elt", $link="/05_c4_workflow/01_core/09_external_integrations/01_elt/")
System(dadata, "Dadata", "Ddadata", $link="/05_c4_workflow/01_core/09_external_integrations/02_dadata/")
System(kontur, "Kontur", "Kontur", $link="/05_c4_workflow/01_core/09_external_integrations/03_kontur/")
System(auto_ru, "Auto ru", "Auto ru", $link="/05_c4_workflow/01_core/09_external_integrations/04_auto_ru/")
System(autoteka, "Autoteka", "Autoteka", $link="/05_c4_workflow/01_core/09_external_integrations/05_autoteka/")
System(kia_myservice, "Kia myservice", "Kia myservice", $link="/05_c4_workflow/01_core/09_external_integrations/06_kia_myservice/")
System(fetm, "Fetm", "Fetm", $link="/05_c4_workflow/01_core/09_external_integrations/07_fetm/")

Rel_R(core, external_integrations, "")

Rel_D(external_integrations, elt, "")
Rel_D(external_integrations, dadata, "")
Rel_D(external_integrations, kontur, "")
Rel_U(external_integrations, auto_ru, "")
Rel_U(external_integrations, autoteka, "")
Rel_U(external_integrations, kia_myservice, "")
Rel_U(external_integrations, fetm, "")

@enduml
----

