---
title: "Active Derectory (Службы каталогов)"
description: "Active Derectory (Службы каталогов)"
weight: 1
draft: false
---

:toc: auto
:toc-title: Содержание
:toclevels: 5
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/
:imgdir: /02_02_05_01_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_02_05_01_img/

= Active Derectory (Службы каталогов)

{empty} +

****
Служба *Active Directory* используется в проекте *Rolf* совместно c link:/02_architecture/02_backend/04_db-redis/[*Redis*, window=_blank] и link:/02_architecture/02_backend/06_idm-keycloak/[*IDM KeyCloak*, window=_blank] для управления учетными записями.
****

====
IMPORTANT: Знаком icon:check-circle[role=green] отмечены активности которые *ВОЙДУТ* в MVP на МАРТ 2023 года!!! +
Знаком icon:minus-circle[role=red] отмечены активности которые *[red]#НЕ# ВОЙДУТ в* MVP на МАРТ 2023 года!!!
====

[[ID-4]]
== Задачи решаемые модулем ID-4 footnote:ID-4[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*ID-4. Управление пользователями системы*#] по управлению пользователями системы

****
*Работа с базой пользователей*
[.green.background]
====
* Табличное отображение icon:check-circle[role=green]
====
[.red.background]
====
. Фильтрация по выбранным параметрам icon:minus-circle[role=red]
. Сортировка icon:minus-circle[role=red]
. Создание / Редактирование / Удаление рабочих групп icon:question-circle[role=blue]
====
****
****
*Работа с карточкой пользователя*
[.green.background]
====
. Получение и вывод данных о пользователе icon:check-circle[role=green]
. Привязка сотрудника к ДЦ icon:check-circle[role=green] (если нельзя ориентироваться на SAP) 
. Привязка сотрудника к отделу icon:check-circle[role=green] (если нельзя ориентироваться на SAP)
. Создание и редактирование рабочего графика пользователя icon:check-circle[role=green]
. Доверенность на продажу ТМЦ: создание именной доверенности и загрузка в КП icon:check-circle[role=green]
====
[.red.background]
====
. Редактирование части данных о пользователе  icon:minus-circle[role=red]
. Просмотр и редактирование ролей пользователя icon:minus-circle[role=red]
. Добавление пользователя в рабочие группы *One Rolf* icon:question-circle[role=blue]
====
****
****
*Права доступа One Rolf*
[.green.background]
====
. Создание и редактирование ролей доступа icon:check-circle[role=green]
. Добавление пользователя к одной или более роли icon:check-circle[role=green]
====
[.red.background]
====
. Реестр ролей *One Rolf* с указанием условий и соответствующих кодов должности icon:minus-circle[role=red]
. Просмотр всех пользователей в разрезе выбранной роли icon:minus-circle[role=red]
. Аттестация для доступа к выделенному модулю icon:minus-circle[role=red]
====
****
****
*Интеграции внешние и внутренние*
[.green.background]
====
. SAP HR icon:check-circle[role=green]
. AD (Active Directory) icon:check-circle[role=green]
. Web Сервис (графики мастеров) icon:check-circle[role=green]
====
[.red.background]
====
. ARMS icon:question-circle[role=blue]
. новый сервис распределения ролей: на MVP *AD* + *Keyclock* в итоговом продукте: пишем новый модуль в Onerolf icon:minus-circle[role=red]
. WEB Tutor icon:minus-circle[role=red]
. ССД icon:question-circle[role=blue]
====
****

[[SERV-1]]
== Задачи решаемые модулем SERV-1 footnote:SERV-1[Документ в Confluence ROLF: [blue]#*MVP Функционал Продукта One Rolf + MDM + MES + WMS|TMS (Новая версия Ноябрь 2022)*#, Название модуля системы: [blue]#*SERV-1. Авторизация | Личный кабинет*#] по управлению авторизацией и личным кабинетом

****
[.green.background]
====
* Авторизация и выход из системы icon:check-circle[role=green]
* КС глазами авторизованного пользователя. Просмотр своего профиля в котором указаны:
. ФИО icon:check-circle[role=green]
. Должность icon:check-circle[role=green]
. Руководитель icon:check-circle[role=green]
. Подчиненные icon:check-circle[role=green]
. Рабочие группы icon:check-circle[role=green]
. Город icon:check-circle[role=green]
. Локация icon:check-circle[role=green]
. ДЦ icon:check-circle[role=green]
. Рабочий день: активен, не активен icon:check-circle[role=green]
. Статус "Онлайн" / "Офлайн" icon:check-circle[role=green]
. Уведомления о новых задачах (браузер или веб пуши или альтернатива) icon:check-circle[role=green]
====
[.red.background]
====
* КС глазами авторизованного пользователя. Просмотр своего профиля в котором указаны:
. Уровень доступа в системе icon:minus-circle[role=red]
. Привязанные бренды icon:minus-circle[role=red]
. Статус: работает, отпуск, больничный, декрет, уволен. icon:minus-circle[role=red]
. Пройденные аттестации из Web Tutor icon:minus-circle[role=red]
. Добавление, редактирование и удаление фото в своём профиле. icon:minus-circle[role=red]
. Добавление, редактирование и удаление личного телефона в своём профиле. icon:minus-circle[role=red]
====
****
****
*Интеграции внешние и внутренние*
[.green.background]
====
. AD icon:check-circle[role=green]
. Sap HR icon:check-circle[role=green]
====
[.red.background]
====
* Web Tutor icon:minus-circle[role=red]
====
****

== Active Derectory (Службы каталогов)
---

{empty} +

*Active Directory* («Активный каталог», *AD*) — службы каталогов корпорации *Microsoft* для операционных систем семейства *Windows Server*. Первоначально создавалась, как *LDAP*-совместимая реализация службы каталогов, однако, начиная с *Windows Server 2008*, включает возможности интеграции с другими службами авторизации, выполняя для них интегрирующую и объединяющую роль. Позволяет администраторам использовать, *групповые политики* footnote:[*Групповая политика* — это набор правил или настроек, в соответствии с которыми производится настройка рабочей среды приёма/передачи (*Windows*, *X-unix* и другие операционные системы с поддержкой сети). Групповые политики создаются в домене и реплицируются в рамках домена. *Объект групповой политики* (англ. Group Policy Object, GPO) состоит из двух физически раздельных составляющих: *контейнера групповой политики* (англ. Group Policy Container, GPC) и *шаблона групповой политики* (англ. Group Policy Template, GPT). Эти два компонента содержат в себе все данные о параметрах рабочей среды, которая включается в состав объекта групповой политики. Продуманное применение объектов GPO к объектам каталога *Active Directory* позволяет создавать эффективную и легко управляемую компьютерную рабочую среду на базе ОС Windows. Политики применяются сверху вниз по иерархии каталога *Active Directory*.] для обеспечения единообразия настройки пользовательской рабочей среды, разворачивать программное обеспечение на множестве компьютеров через групповые политики или посредством *System Center Configuration Manager* (ранее — *Microsoft Systems Management Server*), устанавливать обновления операционной системы, прикладного и серверного программного обеспечения на всех компьютерах в сети, используя Службу обновления *Windows Server*. Хранит данные и настройки среды в централизованной базе данных. Сети *Active Directory* могут быть различного размера: от нескольких десятков до нескольких миллионов объектов.

{empty} +

Представление решения состоялось в 1999 году, впервые продукт был выпущен вместе с *Windows 2000 Server*, а затем развит в рамках выпуска *Windows Server 2003*. Впоследствии новые версии продукта вошли в *Windows Server 2003 R2*, *Windows Server 2008* и *Windows Server 2008 R2* и переименован в *Active Directory Domain Services*. Ранее служба каталогов называлась *NT Directory Service* (*NTDS*), это название до сих пор можно встретить в некоторых исполняемых файлах.

{empty} +

В отличие от версий *Windows* до *Windows 2000*, которые использовали в основном протокол *NetBIOS* для сетевого взаимодействия, служба *Active Directory* интегрирована с *DNS* и работает только поверх *TCP/IP*. Для аутентификации по умолчанию используется протокол *Kerberos*. Если клиент или приложение не поддерживает *Kerberos*-аутентификацию, используется протокол *NTLM*.

{empty} +

Для разработчиков программного обеспечения предоставляется программный интерфейс доступа к службам *Active Directory* — *ADSI*.

== Устройство
---

=== Объекты

*Active Directory* имеет иерархическую структуру, состоящую из объектов. Объекты разделяются на три основные категории: ресурсы (например, принтеры), службы (например, электронная почта) и учётные записи пользователей и компьютеров. Служба предоставляет информацию об объектах, позволяет организовывать объекты, управлять доступом к ним, а также устанавливает правила безопасности.

{empty} +

Объекты могут быть хранилищами для других объектов (группы безопасности и распространения). Объект уникально определяется своим именем и имеет набор атрибутов — характеристик и данных, которые он может содержать; последние, в свою очередь, зависят от типа объекта. Атрибуты являются составляющей базой структуры объекта и определяются в схеме. Схема определяет, какие типы объектов могут существовать.

{empty} +

Сама схема состоит из двух типов объектов: объекты классов схемы и объекты атрибутов схемы. Один объект класса схемы определяет один тип объекта *Active Directory* (например, объект «Пользователь»), а один объект атрибута схемы определяет атрибут, который объект может иметь.

{empty} +

Каждый объект атрибута может быть использован в нескольких разных объектах классов схемы. Эти объекты называются объектами схемы (или метаданными footnote:[*Метаданные* (от др.-греч. μετά «за, после, рядом, в середине» и данные) — информация о другой информации, или данные, относящиеся к дополнительной информации о содержимом или объекте. Метаданные раскрывают сведения о признаках и свойствах, характеризующих какие-либо сущности, позволяющие автоматически искать и управлять ими в больших информационных потоках.]) и позволяют изменять и дополнять схему, когда это необходимо и возможно. Однако каждый объект схемы является частью определений объектов, поэтому отключение или изменение этих объектов могут иметь серьёзные последствия, так как в результате этих действий будет изменена структура каталогов. Изменение объекта схемы автоматически распространяется в службе каталогов. Будучи однажды созданным, объект схемы не может быть удалён, он может быть только отключён. Обычно все изменения схемы тщательно планируются.

{empty} +

Контейнер аналогичен объекту в том смысле, что он также имеет атрибуты и принадлежит пространству имён, но, в отличие от объекта, контейнер не обозначает ничего конкретного: он может содержать группу объектов или другие контейнеры.

=== Структура

Верхним уровнем структуры является лес — совокупность всех объектов, атрибутов и правил (синтаксиса атрибутов) в *Active Directory*. Лес содержит одно или несколько деревьев, связанных транзитивными отношениями доверия. Дерево содержит один или несколько доменов, также связанных в иерархию транзитивными отношениями доверия. Домены идентифицируются своими структурами имён *DNS* — пространствами имён.

{empty} +

Объекты в домене могут быть сгруппированы в контейнеры — подразделения. Подразделения позволяют создавать иерархию внутри домена, упрощают его администрирование и позволяют моделировать, например, организационную или географическую структуру организации в службе каталогов. Подразделения могут содержать другие подразделения. *Microsoft* рекомендует использовать как можно меньше доменов в службе каталогов, а для структурирования и политик использовать подразделения. Часто групповые политики применяются именно к подразделениям. Групповые политики сами являются объектами. Подразделение является самым низким уровнем, на котором могут делегироваться административные полномочия.

{empty} +

Другим способом деления являются сайты, которые являются способом физической (а не логической) группировки на основе сегментов сети. Сайты подразделяются на имеющие подключения по низко скоростным каналам (например, по каналам глобальных сетей, с помощью виртуальных частных сетей) и по высокоскоростным каналам (например, через локальную сеть). Сайт может содержать один или несколько доменов, а домен может содержать один или несколько сайтов. При проектировании службы каталогов важно учитывать сетевой трафик, создающийся при синхронизации данных между сайтами.

{empty} +

Ключевым решением при проектировании службы каталогов является решение о разделении информационной инфраструктуры на иерархические домены и подразделения верхнего уровня. Типичными моделями, используемыми для такого разделения, являются модели разделения по функциональным подразделениям компании, по географическому положению и по ролям в информационной инфраструктуре компании. Часто используются комбинации этих моделей.

=== Физическая структура и репликация

Физически информация хранится на одном или нескольких равнозначных контроллерах доменов, заменивших использовавшиеся в *Windows NT* основной и резервные контроллеры домена, хотя для выполнения некоторых операций сохраняется и так называемый сервер «операций с одним главным сервером», который может эмулировать главный контроллер домена. Каждый контроллер домена хранит копию данных, предназначенную для чтения и записи. Изменения, сделанные на одном контроллере, синхронизируются на все контроллеры домена при репликации. Серверы, на которых сама служба *Active Directory* не установлена, но которые при этом входят в домен *Active Directory*, называются рядовыми серверами.

{empty} +

Репликация каталога выполняется по запросу. Служба *KCC* (*Knowledge Consistency Checker*) создаёт топологию репликации, которая использует сайты, определённые в системе, для управления трафиком. Внутрисайтовая репликация выполняется часто и автоматически с помощью средства проверки согласованности (уведомлением партнёров по репликации об изменениях). Репликация между сайтами может быть настроена для каждого канала сайта (в зависимости от качества канала) — различная «оценка» (или «стоимость») может быть назначена каждому каналу (например, *DS3*, *T1*, *ISDN*), и трафик репликации будет ограничен, передаваться по расписанию и маршрутизироваться в соответствии с назначенной оценкой канала. Данные репликации могут транзитом передаваться через несколько сайтов через мосты связи сайтов, если «оценка» низка, хотя *AD* автоматически назначает более низкую оценку для связей «сайт—сайт», чем для транзитных соединений. Репликация "сайт—сайт" выполняется серверами-плацдармами в каждом сайте, которые затем реплицируют изменения на каждый контроллер домена своего сайта. Внутридоменная репликация проходит по протоколу *RPC*, междоменная — может использовать также протокол *SMTP*.

{empty} +

Если структура *Active Directory* содержит несколько доменов, для решения задачи поиска объектов используется глобальный каталог: контроллер домена, содержащий все объекты леса, но с ограниченным набором атрибутов (неполная реплика). Каталог хранится на указанных серверах глобального каталога и обслуживает междоменные запросы.

{empty} +

Возможность операций с одним главным компьютером позволяет обрабатывать запросы, когда репликация с несколькими главными компьютерами недопустима. Есть пять типов таких операций: эмуляция главного контроллера домена (*PDC*-эмулятор), главный компьютер относительного идентификатора (мастер относительных идентификаторов или *RID*-мастер), главный компьютер инфраструктуры (мастер инфраструктуры), главный компьютер схемы (мастер схемы) и главный компьютер именования домена (мастер именования доменов). Первые три роли уникальны в рамках домена, последние две — уникальны в рамках всего леса.

{empty} +

Базу *Active Directory* можно разделить на три логических хранилища или «раздела». Схема является шаблоном для службы и определяет все типы объектов, их классы и атрибуты, синтаксис атрибутов (все деревья находятся в одном лесу, потому что у них одна схема). Конфигурация является структурой леса и деревьев *Active Directory*. Домен хранит всю информацию об объектах, созданных в этом домене. Первые два хранилища реплицируются на все контроллеры доменов в лесу, третий раздел полностью реплицируется между репликами контроллеров в рамках каждого домена и частично — на сервера глобального каталога.

{empty} +

База данных (хранилище каталогов) в *Windows 2000* использует расширяемую подсистему хранения *Microsoft Jet Blue* (англ.), которая позволяет для каждого контроллера домена иметь базу размером до 16 терабайт и 1 миллиард объектов (теоретическое ограничение, практические тесты выполнялись только с приблизительно 100 миллионами объектов). Файл базы называется *NTDS.DIT* и имеет две основные таблицы — таблицу данных и таблицу связей. В *Windows Server 2003* добавлена ещё одна таблица для обеспечения уникальности экземпляров дескрипторов безопасности.

=== Именование

Служба поддерживает следующие форматы именования объектов: универсальные имена типа *UNC*, *URL* и *LDAP URL*. Версия *LDAP* формата именования *X.500* используется внутри службы.

{empty} +

Каждый объект имеет выделенное имя (англ. *distinguished name*, *DN*). Например, объект принтера с именем *HPLaser3* в подразделении *«Маркетинг»* и в домене *foo.org* будет иметь следующее выделенное имя: *CN=HPLaser3,OU=Маркетинг,DC=foo,DC=org*, где *CN* — это общее имя, *OU* — раздел, *DC* — класс объекта домена. Выделенные имена могут иметь намного больше частей, чем четыре части в этом примере. У объектов также есть канонические имена. Это различающиеся имена, записанные в обратном порядке, без идентификаторов и с использованием косых черт в качестве разделителей: *foo.org/Маркетинг/HPLaser3*. Чтобы определить объект внутри его контейнера, используется относительное выделенное имя: *CN=HPLaser3*. У каждого объекта также есть глобально уникальный идентификатор (*GUID*) — уникальная и неизменная 128-битная строка, которая используется в *Active Directory* для поиска и репликации. Определённые объекты также имеют имя участника-пользователя (*UPN*, в соответствии с *RFC 822*) в формате объект@домен.

=== Интеграция с UNIX

Различные уровни взаимодействия с *Active Directory* могут быть реализованы в большинстве *UNIX*-подобных операционных систем посредством *LDAP*-клиентов, но такие системы, как правило, не воспринимают большую часть атрибутов, ассоциированных с компонентами *Windows*, например, групповые политики и поддержку односторонних доверенностей. Однако с выходом *Samba 4* появилась возможность использовать групповые политики и инструменты администрирования *Windows*.

{empty} +

Добавления в схему, поставляемые с *Windows Server 2003 R2*, включают атрибуты, которые достаточно тесно связаны с *RFC 2307*, чтобы использоваться в общем случае. Базовые реализации *RFC 2307* — *nss_ldap* и *pam_ldap*, предложенные *PADL.com*, непосредственно поддерживают эти атрибуты. Стандартная схема для членства в группе соответствует *RFC 2307bis*. *Windows Server 2003 R2* включает Консоль управления *Microsoft* для создания и редактирования атрибутов.

{empty} +

*Active Directory* автоматизируются с помощью *Powershell*.