[plantuml%interactive,"flora_ext",format=svg,align=center,width=60%]
.Flora - Флора и внешние системы
----
@startuml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml
!include static/includes/c4_component.puml

skinparam backgroundcolor transparent
skinparam minClassWidth 200
'skinparam linetype ortho

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

System(rolf, "ROLF", "ROLF", $link="/06_c4_infrastructure/")

Person(user, "USER", "Пользователь")
Person(admin, "ADMIN", "Администратор")

Container_Ext(centrifugo, "Centrifugo WSS", "Centrifugo WSS")
Container_Ext(smtp, "SMTP Server", "SMTP Server")
Container_Ext(sms, "SMS Gate", "SMS Gate")
Container_Ext(keycloak, "Keycloak", "Keycloak")
Container_Ext(ad, "Active Directory", "Active Directory")
System_Ext(saphr, "SAP HR", "SAP HR")
Container_Ext(grafana, "Grafana", "Grafana")
System_Ext(wms, "WMS", "WMS")
System_Ext(mdm, "MDM", "MDM")
System_Ext(fishblue, "FishBlue", "FishBlue")
System_Ext(is_shtorm, "ИС Шторм", "ИС Шторм")
System_Ext(as_rolf, "АС Рольф", "АС Рольф")
System_Ext(as_rolf_strah, "АС Рольф Страхование", "АС Рольф Страхование")
Container_Ext(payment_gate, "Платежный шлюз", "Платежный шлюз")

System(flora, "FLORA", "Система Flora", $link="/06_c4_infrastructure/02_flora/")

Rel_L(user, flora, "")
Rel_L(admin, flora, "")

BiRel_R(rolf, flora, "")

BiRel_D(flora, centrifugo, "")
BiRel_D(flora, smtp, "")
BiRel_D(flora, sms, "")
BiRel_D(flora, keycloak, "")
BiRel_D(flora, ad, "")
BiRel_D(flora, saphr, "")
BiRel_D(flora, grafana, "")

BiRel_U(flora, wms, "")
BiRel_U(flora, mdm, "")
BiRel_U(flora, fishblue, "")
BiRel_U(flora, is_shtorm, "")
BiRel_U(flora, as_rolf, "")
BiRel_U(flora, as_rolf_strah, "")
BiRel_U(flora, payment_gate, "")

@enduml
----

