---
title: "ИС Шторм"
description: "ИС Шторм"
weight: 2
draft: false
Categories:
    - Architecture
    - Backend
Tags:
    - Opersystems
    - Shtorm
---

:imgdir: /04_02_06_02_img/
:imagesoutdir: ./static/04_02_06_02_img/

include::static/includes/init.adoc[]



= ИС Шторм

{empty} +

== Общие сведения

****
Программное обеспечение *ШТОРМ* (далее – Программа, Система) для автоматизации бизнес-процессов:
====
* Продажи новых *А/М*
* Планирования слесарного производства
====
****

****
Для функционирования программы необходимо следующее программное обеспечение:
====
* *Серверная часть*: *СУБД Oracle* версии *10*
* *Клиентская часть*: операционная система *Microsoft Windows* версии не младше *XP*, *Oracle Client* с компонентой *ODP.NET* версии *10 (строго)*, *Microsoft .NET Framework Runtime* версии не ниже *4.0*, установленные приложения *MS Office Word* и *MS Office Excel* версии не ниже *2010*
====
****

****
Реализация *серверной логики* написана на языке *PL/SQL* в среде *СУБД Oracle*.
*Клиентская часть* разработана на языке программирования *C#* с использованием интерфейса программирования *Microsoft .NET Windows Forms* в среде разработки приложений *Microsoft Visual Studio версии 12* с применением библиотеки разработки пользовательских интерфейсов link:http://www.devexpress.com[DevExpress, window=_blank] версии *11*.
****

== Функциональное назначение

****
Функционально система разделена на два блока:
====
* Блок *Управление продажами новых А/М*
* Блок *Планирование слесарного производства*
====
****

=== Управление продажами новых А/М

****
Блок *Управление продажами новых А/М* предназначен для автоматизации следующих ключевых бизнес-процессов:
====
* Формирование и ведение справочной информации о субъектах и объектах деятельности и их количественных и качественных характеристиках
* Формирование и ведения списка доступных *А/М* – стока
* Учёт клиентского трафика и управление т.н. воронкой продаж
* Формирование и ведение перечня взаимосвязанных документов, отражающих ключевые элементы бизнес-процесса продаж
* Учёт качественных/количественных характеристик и показателей в рамках процесса управления программой лояльности клиентов
====
****

=== Планирование слесарного производства

****
Блок *Планирование слесарного производства* предназначен для автоматизации следующих ключевых бизнес-процессов:
====
* Учет графиков работ мастеров-консультантов и механиков
* Создание визита в сервис, ПСО
* Автоматическое планирование загрузки слесарного цеха с учетом ограничений по количеству работ, времени и нагрузки на мастера-консультанта, механика
* Автоматическое планирование также постов мойки и уборки
* Планирование выдачи автомобиля
* Просмотр мастером цеха загрузку цеха, план приема автомобилей на день
* Просмотр сервисным консультантом свой детальный план работы на день (список приемок/выдач)
* Возможность отметиться о стадии выполняемых работ механиком, мастером-консультантом, постами мойки и уборки (отметки сразу-же отображаются в соответствующих окнах)
* Отдельная программа для отметок о о выполняемых работах для механиков, мастеров-консультантов, мойщиков и уборщиков
* Отдельная программа экрана приемки/выдачи (информация в клиентской зоне)
* Отдельная программа статуса цеха (может использоваться в цехе вместо доски планирования для механиков)
====
****

== Описание логической структуры

=== Общая структура приложения

****
С точки зрения общей архитектуры Программа представляет собой двухзвенное клиент-серверное приложение. +
Данные хранятся и обрабатываются в базе данных под управлением *СУБД Oracle*, пользовательский интерфейс для работы с данными реализует клиентское приложение, разработанное на платформе *Microsoft .Net* с интерфейсом *Windows Forms*.
Клиентское приложение взаимодействует с сервером *БД* через *API ODP.NET*, который является высокоуровневым интерфейсом к стандартному *OCI*-клиенту *СУБД Oracle*.
****

=== Общая структура серверной части приложения

****
Для хранения и обработки данных на стороне сервера *БД* выделены отдельные схемы. В части блока *Управление продажами новых А/М* схемы, как правило, названы по именам соответствующих брендов (*AUDI*, *SKODA*, *MERCEDES* и т.д.). При этом принципиально важным является следующее: внутри выделенной для бренда схемы может работать только этот выделенный бренд. Мультибренд внутри одной схемы *БД* в части блока *Управление продажами новых А/М* не реализован. Исторически это связано с высокой интенсивностью и, вместе с тем, неопределённостью с планами развития Системы в *2011* году. С одной стороны стало появляться всё больше и больше *ДЦ*, которые хотели использовать механизм управления продажами, реализованный в *Шторме*, с другой – продолжался проект *ADP*, в связи с чем однозначного решения по единой системе *РОЛЬФ* Розницы на тот момент принято не было. Как результат, за довольно короткий срок (с марта по декабрь *2011* года) Система была развёрнута для брендов *AUDI*, *SKODA*, *MERCEDES*, *HYUNDAI*, *TOYOTA*, *LEXUS*, *MAZDA*, и перевод всех экземпляров системы на работу в режиме Мультибренд стал существенной архитектурной и технической задачей, которая до сих пор не решена.

{empty} +

Одним из основных минусов такой архитектуры является дублирование кода, реализующего похожий функционал в разных брендах. Чем больше количество новых брендов, тем больше схем – тем больше степень дублирования.

{empty} +

Отдельно стоит упомянуть схему *CJD* для трёх брендов: *Chrysler*, *Jeep* и *Dodge*. Эта схема также не является исключением из принципа монобрендовости блока *Управление продажами*. Возможность работы с несколькими брендами в этой схема реализована исключительно путём объединения моделей трёх разных марок под один искусственно созданный бренд *CJD*.

{empty} +

В части блока *Планирование слесарного производства* применена архитектура *одна схема – много брендов/дц/цехов*. Такая архитектура выбрана, чтобы запрограммировать слесарное производство всей сети дилерских центров, каждый из которых может работать с несколькими брендами и, независимо от брендов, одним или несколькими слесарными цехами. Последние могут обслуживать какой-то конкретный бренд или быть мультибрендовыми.

{empty} +

Чтобы не _"ломать"_ архитектуру клиентской программы *ШТОРМ*, везде, где можно используются прямые ссылки на общую схему блока *Планирование слесарного производства* *STORM_SERVICE*. В исключительных случаях делаются так называемые заглушки в *брендовых* схемах, которые ведут в схему *STORM_SERVICE*.

{empty} +

Также в связи с такой архитектурой были разработаны механизмы единого хранения всех *ДЦ*, брендов и пользователей в схеме блока *Планирование слесарного производства*, так как в каждой *брендовой* схеме соответствующие идентификаторы повторяются.

{empty} +

Общая архитектура *Системы* построена таким образом, что максимум возможной логики работы с данными осуществляется на стороне сервера. Для реализации серверной логики используются хранимые процедуры, функции, триггеры. Пакеты применяются в редких случаях, в основном там, где есть возможность группировки элементарных операций в общие блоки с единым уровнем доступа.
****

=== Общая структура клиентской части приложения

****
Основной проект, содержит реализацию объектов блока *Управление продажами новых А/М* (3.10), Блока *Лояльность*. Проект реализовывает архитектуру *Мультибренд* (подробнее в 3.5), в связи с чем, хранение файлов организовано с учетом данной архитектуры. +
Структура хранения файлов проекта:

[%header, cols="^.^20,.^80"]
|===
^.^|Название папки ^.^| Описание содержимого

| *Classes* | Содержит свободные классы, не привязанные к конкретным формам или пользовательским элементам проекта. Внутри содержит только подпапки по брендам и общую всех брендов папку.
| *Classes\ALL* | Содержит классы общие для всех брендов. Содержит подпапки для удобства работы с файлами и группировки их. 
| *Classes\<Бренд>* | Содержит индивидуальные экземпляры классов для бренда. Структура папки соответствует структуре общей папки ALL.
| *Forms* | Содержит формы и пользовательские элементы. Внутри содержит только подпапки по брендам и общую всех брендов папку.
| *Forms\ALL* | Содержит формы и пользовательские элементы общие для всех брендов. Содержит подпапки для удобства работы с файлами и их группировки. 
| *Forms\<Бренд>* | Содержит формы и пользовательские элементы для бренда. Структура папки соответствует структуре общей папки ALL.
| *Templates* | Содержит шаблоны для настройки вида таблиц. Разделение по брендам организовано на уровне имени файла.
|===

{empty} +

Все классы библиотеки расположены в пространстве имен iAvto. Все общие формы библиотеки расположены в пространстве имен iAvto.Forms. 
****
