[plantuml%interactive,"annotations",format=svg,align=center,width=30%]
.Comments - Комментарии
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'left to right direction

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent

<style>
System {
    MinimumWidth 300
    MinimumHeight 150
}
</style>

LAYOUT_TOP_DOWN()

'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()
'LAYOUT_LANDSCAPE()

System(coreapp, "Coreapp", "Комментарии, датагриды", $link="/05_c4/01_core/01_coreapp/")
System(annotations, "Annotations", "Аннотации")

Rel_U(annotations, coreapp, "")

@enduml
----

