[plantuml%interactive,"carts",format=svg,align=center,width=30%]
.Carts - Базы данных
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(needs_and_orders, "Needs and orders", "Обращения, потребности, предложения", $link="/05_c4_workflow/01_core/03_needs_and_orders/")
System(carts, "Carts", "Базы данных")

Rel_U(carts, needs_and_orders, "")

@enduml
----


