---
title: "Tinkoff"
description: "Tinkoff"
weight: 5
draft: false
Categories:
    - Architecture
    - Backend
Tags:
    - External system services
    - Tinkoff
---

:imgdir: /02_02_07_05_img/
:imagesoutdir: ./static/02_02_07_05_img/

include::static/includes/init.adoc[]

= Tinkoff

{empty} +

****
.Коллекция *Postman*
[[collection_1_postman_anchor]]
[%collapsible%close]
====
[source, json]
----
include::static/02_02_07_05_img/tinkoff_postman_collection.json[]
----
====
****

****
* `*link:tinkoff_broker_api_v_1_5_1.pdf[Скачать документацию по методам, window=_blank]*`
* `*link:catalog_broker_api_v1_3.xls[Скачать справочник по методам, window=_blank]*`
****

== Tinkoff

****
Данный раздел описывает требования к интеграционному взаимодействию между *OneRolf* и *Tinkoff* в рамках работ по реализации проекта по разработке Оперсистемы по принципу `"единого окна"` для оформления финансовых продуктов и постпродажного сопровождения.

{empty} +

Целью запуска интеграционного взаимодействия между *OneRolf* и *Tinkoff*-страхование является предварительный, первичный, финальный расчет страховых и дополнительных продуктов, а так же выпуск соответствующих документов.
****

== Страховые продукты

=== Общие методы

****
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/01_token_auth_from_partner/[tokenAuthFromPartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/02_get_policy_info_by_set_number_partner/[getPolicyInfoBySetNumberPartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/03_get_pack_documents_for_print_partner/[getPackDocumentsForPrintPartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/04_approve_conclusion_partner/[approveConclusionPartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/05_send_confirm_payment_partner/[sendConfirmPaymentPartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/06_cancel_policy_request/[cancelPolicy, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/07_upload_file_partner/[uploadFilePartner, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/01_common/08_send_scan_doc_partner/[sendScanDocPartner, window=_blank]*`
****

=== Работа с продуктами

****
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/02_products/01_calc_partner_fquote/[calcPartnerFQuote, window=_blank]*`
* `*link:https://doc-integration-main.com-dev.int.rolfcorp.ru/02_integrations/07_tinkoff/01_insurance_products/02_products/02_issue_quote_set_partner/[issueQuoteSetPartner, window=_blank]*`
****

=== SSL Сертификат

****
Для взаимодействия с *API Тинькофф* Страхование необходимо использовать *SSL* сертификат:
====
* `*link:ao_rolf_2023.crt[Скачать сертификат, window=_blank]*`
* `*link:private.key[Скачать закрытый ключ, window=_blank]*`
====
****

====
IMPORTANT: Пароль от секретного ключа можно уточнить у: `*Евгений Реутов*`, `*Головин Денис*`
====

== Кредитные продукты

=== Коллекция Postman

****
.Коллекция *Postman*
[[collection_2_postman_anchor]]
[%collapsible%close]
====
[source, json]
----
include::static/02_02_07_05_img/tinkoff_credit_postman_collection.json[]
----
====
****

****
`*link:tinkoff_credit_api.docx[Скачать документацию по методам, window=_blank]*`
****

====
IMPORTANT: На текущий момент по предоставленной документации по флоу кредита возможно:
****
* Создание заявки
* Обогащение заявки данными
* Первый этап обогащения - передача данных: *`Условия кредита`*, *`Контактная информация`*, *`Данные ТС`*
* Второй этап обогащения - передача данных: *`Детальная Контактная информация`*, *`Паспортные данные`*, *`Адрес регистрации`*, *`Адрес фактического проживания`*
* Отправка заявки на рассмотрение в *Тинькофф*
* Получение статусов по заявке
* Дальнейшая работа с заявкой в *TCB* (*Tincoff Credit Broker*).
****
====

==== Порядок вызова методов

****
[cols=".^15,.^85"]
|===
| URL test | `*link:https://qa.forma.tcsbank.ru/api/autobroker/v1/cobroker/app[window=_blank]*`
| URL prod | `*link:https://forma.tinkoff.ru/api/autobroker/v1/cobroker/app[window=_blank]*`
|===
****

****
* `*create*` - Создаем заявку
* `*next*` - Обогащаем заявку данными клиента в *2* этапа
* `*push*` - Отправляем заявку на рассмотрение
* `*status*` - Получаем статус по заявке
****

==== Остальные методы в Swagger

====
IMPORTANT: Следующие методы присутствуют в документации *Swagger*, но не заявлены коллегами *Тинькофф* как поддерживаемые на текущий момент.
====

****
* `*cancel*` - Отменяем заявку
* `*offerParams*` - Получаем офферы по заявке
* `*resume*` - Получаем данные по заявке
* `*upload*` - Прикладываем файл к заявке
* `*autofill/start*` - Старт предзаполнения
* `*autofill/check*` - Проверка статуса предзаполнения
****

==== Методы Справочника ТС

****
`*{tinkoffUrl} = ‘/api/reference/car/’*`
****

====
IMPORTANT: Следующие методы необходимы для получения данных из Справочника *ТС Тинькофф*. По текущей документации *Тинькофф* данные из справочника необходимы при создании заявки методом `*create*`, при этом коллеги отметили, что данные по *ТС* (*id* марки/модели) необязательны при создании заявки.
====

****
* `*search*` - поиск данных *ТС*
* `*generations*` - получение списка поколений *ТС*
* `*configurations*` - получение списка конфигураций *ТС*
* `*price*` - получение приближенной/точной цены *ТС*
** точность цены зависит от передаваемых параметров
****

== Модуль FETM

****
*FETM* (*Flora Entity Transformation Module*) - это програмный модуль продукта *Flora*, направленный на взаимодействия со страховыми и финансовыми компаниями для оформления страховых и финансовых продуктов, а так же кредитов.
****

=== Алгоритм работы

****
.*Схема взаимодействия с Tinkoff (Отобразить/Скрыть)*
[%collapsible%close]
====
++++
<iframe frameborder="0" style="width:100%;height:1000px;" src="https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Rolf_Tinkoff_components_Schema_v3.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1H9ZuHQixEtas1LPV1t2wIy_v8AkJLE-l%26export%3Ddownload"></iframe>
++++
====
****

****
При взаимодействии сервисов *Flora*, модуля *FETM* и *СК* выделяются следующие потоки данных:
====
. Ввод данных со стороны пользователя для формирования запросов в *СК/КО*
. Трансформация запроса *FrontEnd -> СК/КО*
. Получение результатов расчета от *СК/КО*
. Трансформация результата расчета *СК/КО -> FrontEnd*
. Сохранение результатов расчета. Формирование сообщения для отправки на *FrontEnd*
. Вывод данных
====
****

=== Поток 1

****
. Пользователь взаимодействует с *FrontEnd Flora*.
. *FrontEnd* взаимодействует с *Platformeco-FI* по *https*.
. *Platformeco-FI* определяет тип интеграции, для выбранного пользователем продукта, по признаку `*is_direct_integration*` в таблице `*flora_f_and_i.f_and_i_insurance_companys_products_d*`.
. *Platformeco-FI* создает в *БД* заказ в таблицах: `*flora_needs_and_orders.needs_and_orders_b*`, `*flora_f_and_i.f_and_i_needs_and_orders_b*`. Данные, полученные от *FrontEnd*, записываются в *БД* в таблицу `*flora_f_and_i.f_and_i_needs_and_orders_b*` в виде *JSON*-объекта в поле `*data_as_json*` для соответствующего заказа.
. *Platformeco-FI* создаёт сообщение и отправляет его в соответствующий стадии расчета топик *Kafka* на канале *Platformeco-Integration*.
****

=== Поток 2

****
. При появлении нового события в соответствующем стадии расчета топика *Kafka*, *Platformeco-Integration* читает новое сообщение.
. *Platformeco-Integration* производит трансформацию *JSON* объекта от *FrontEnd* в объект для отправки в *СК/КО*.
. *Platformeco-Integration* создаёт сообщение и отправляет его в соответствующий стадии расчета топик *Kafka* на канале *Platformeco-Integration*.
****

=== Поток 3

****
. При появлении нового события в соответствующем стадии расчета топика *Kafka*, *Platformeco-Integration* читает новое сообщение.
. *Platformeco-Integration* вызывает соответствующую дифиницию для отправки запроса в соответствующую *СК/КО*.
. *Platformeco-Integration* получает ответ на запрос.
. *Platformeco-Integration* создаёт сообщение, которое содержит ответ от *СК/КО*, и отправляет его в соответствующий стадии расчета топик *Kafka* на канале *Platformeco-Integration*.
****

=== Поток 4

****
. При появлении нового события в соответствующем стадии расчета топика *Kafka*, **Platformeco-Integration** читает новое сообщение.
. *Platformeco-Integration* производит трансформацию *JSON* объекта от *СК/КО* в объект для отправки на *FrontEnd*
. *Platformeco-Integration* создаёт сообщение и отправляет его в соответствующий стадии расчета топик *Kafka* на канале *Platformeco-FI*.
****

=== Поток 5

****
. При появлении нового события в соответствующем стадии расчета топика *Kafka*, *Platformeco-FI* читает новое сообщение.
. *Platformeco-FI* обновляет в *БД* заказ в таблицах: `*flora_needs_and_orders.needs_and_orders_b*`, `*flora_f_and_i.f_and_i_needs_and_orders_b*`. Данные, полученные от *СК/КО*, инсёртсятся в *БД* в таблицу `*flora_f_and_i.f_and_i_needs_and_orders_b*` в виде *JSON*-объекта в поле `*direct_integration_result_json*` для соответствующего заказа.
. *Platformeco-FI* (*Producer*) создаёт сообщение и отправляет его в *Kafka*.
. *Platformeco-FI* создаёт сообщение и отправляет его в соответствующий стадии расчета топик *Kafka* на канале *"Task&Events"*
****

=== Поток 6

****
. При появлении нового события в соответствующем стадии расчета топика *Kafka*, *Platformeco-Task&Events* читает новое сообщение
. ???
****