[plantuml%interactive,"pfanalyzing",format=svg,align=center,width=30%]
.Print forms analyze - Анализ печатных форм
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(pfanalyze, "Print forms analyze", "Анализ печатных форм", $link="/05_c4_workflow/01_core/12_pfanalyze/")
System(pfanalyzing, "Print forms analyze", "Анализ печатных форм")

Rel_U(pfanalyzing, pfanalyze, "")

@enduml
----

