---
title: "База данных PostgreSQL"
description: "База данных PostgreSQL"
weight: 2
draft: false
---

:toc: auto
:toc-title: Содержание
:toclevels: 5
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_02_01_02_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_02_01_02_img/

= База данных PostgreSQL

{empty} +

****
*PostgreSQL* — объектно-реляционная система управления базами данных
*PostgreSQL* — популярная свободная объектно-реляционная система управления базами данных. *PostgreSQL* базируется на языке SQL и поддерживает многочисленные возможности.
****

== Преимущества PostgreSQL

====
. Поддержка БД неограниченного размера
. Мощные и надёжные механизмы транзакций и репликации
. Расширяемая система встроенных языков программирования и поддержка загрузки C-совместимых модулей
. Наследование
. Легкая расширяемость
====

== Текущие ограничения PostgreSQL

====
. Нет ограничений на максимальный размер базы данных
. Нет ограничений на количество записей в таблице
. Нет ограничений на количество индексов в таблице
. Максимальный размер таблицы — 32 Тбайт
. Максимальный размер записи — 1,6 Тбайт
. Максимальный размер поля — 1 Гбайт
. Максимум полей в записи250—1600 (в зависимости от типов полей)
====

== Особенности PostgreSQL

Функции в *PostgreSQL* являются блоками кода, исполняемыми на сервере, а не на клиенте *БД*. Хотя они могут писаться на чистом *SQL*, реализация дополнительной логики, например, условных переходов и циклов, выходит за рамки собственно *SQL* и требует использования некоторых языковых расширений. Функции могут писаться с использованием различных языков программирования. *PostgreSQL* допускает использование функций, возвращающих набор записей, который далее можно использовать так же, как и результат выполнения обычного запроса. Функции могут выполняться как с правами их создателя, так и с правами текущего пользователя. Иногда функции отождествляются с хранимыми процедурами, однако между этими понятиями есть различие.

=== Триггеры

Триггеры в *PostgreSQL* определяются как функции, инициируемые DML-операциями. Например, операция *INSERT* может запускать триггер, проверяющий добавленную запись на соответствия определённым условиям. При написании функций для триггеров могут использоваться различные языки программирования. Триггеры ассоциируются с таблицами. Множественные триггеры выполняются в алфавитном порядке.

=== Механизм правил

Механизм правил в *PostgreSQL* представляет собой механизм создания пользовательских обработчиков не только *DML*-операций, но и операции выборки. Основное отличие от механизма триггеров заключается в том, что правила срабатывают на этапе разбора запроса, до выбора оптимального плана выполнения и самого процесса выполнения. Правила позволяют переопределять поведение системы при выполнении *SQL*-операции к таблице.

=== Индексы

Индексы в *PostgreSQL* следующих типов: *B*-дерево, *хэш*, *R*-дерево, *GiST*, *GIN*. При необходимости можно создавать новые типы индексов, хотя это далеко не тривиальный процесс.

=== Многоверсионность

Многоверсионность поддерживается в *PostgreSQL* — возможна одновременнуя модификация БД несколькими пользователями с помощью механизма **M**ulti**V**ersion **C**oncurrency **C**ontrol (*MVCC*). Благодаря этому соблюдаются требования *ACID*, и практически отпадает нужда в блокировках чтения.

=== Расширение

Расширение *PostgreSQL* для собственных нужд возможно практически в любом аспекте. Есть возможность добавлять собственные преобразования типов, типы данных, домены (пользовательские типы с изначально наложенными ограничениями), функции (включая агрегатные), индексы, операторы (включая переопределение уже существующих) и процедурные языки.

=== Наследование

Наследование в *PostgreSQL* реализовано на уровне таблиц. Таблицы могут наследовать характеристики и наборы полей от других таблиц (родительских). При этом данные, добавленные в порождённую таблицу, автоматически будут участвовать (если это не указано отдельно) в запросах к родительской таблице.