---
title: "Система поиска OpenSearch"
description: "Система поиска OpenSearch"
weight: 5
draft: false
---

:imgdir: /02_02_01_05_img/
:imagesoutdir: ./static/02_02_01_05_img/

include::content/init.adoc[]

= Система поиска OpenSearch

{empty} +

====
IMPORTANT: В *коллекции Postman* для *Debezium* и *OpenSearch* все учётные данные проставлены для *dev* !!!
====

****
.Коллекция *Postman*
[[collection_postman_anchor]]
[%collapsible%close]
====
[source, json]
----
include::static/02_02_01_05_img/opensearch_postman_collection.json[]
----
====
****

== Доступы к системе OpenSearch

****
[cols=".^30,.^10,.^60"]
|===
^.^| Окружение | |

.2+^| `log-search-dev` | Data | `[.blue]#rc1a-12u3pgq5ognod27k.mdb.yandexcloud.net#`
| Dashboard | `[.blue]#c-c9qepe1trei5f7imkupm.rw.mdb.yandexcloud.net#`
.2+^| `log-search-prod` | Data | `[.blue]#rc1a-jk4vs9uauikf93f7.mdb.yandexcloud.net#`
| Dashboard | `[.blue]#c-c9q5kgmketek2uod6tip.rw.mdb.yandexcloud.net#`
.2+^| `telemetry-plf-dev` +
(_тут хрянится трейсы из **PL**_) | Data | `[.blue]#rc1a-o9irn5kf3rgj031l.mdb.yandexcloud.net#`
| Dashboard | `[.blue]#c-c9qsi4u2n12opfh8b4g0.rw.mdb.yandexcloud.net#`
.2+^| `telemetry-plf-prod` +
(_тут хрянится трейсы из **PL**_) | Data | `[.blue]#rc1a-s94res1o5kd4q59s.mdb.yandexcloud.net#` +
`[.blue]#rc1b-m1mr87j2426hlhal.mdb.yandexcloud.net#`
| Dashboard | `[.blue]#c-c9q8o1hr0j5go2ovukur.rw.mdb.yandexcloud.net#`
|===
****

== Система OpenSearch

****
*OpenSearch* — это система поиска и аналитики с открытым исходным кодом, используемая разработчиками для получения, поиска, визуализации и анализа данных. *OpenSearch* состоит из хранилища данных и поисковой системы (*OpenSearch*), визуализации и пользовательского интерфейса (*OpenSearch Dashboards*), а так же сборщика данных на стороне сервера (*Data Prepper*). Пользователи могут предоставить доступ к функциональности *OpenSearch* с помощью набора подключаемых модулей, улучшающих поиск, аналитику, безопасность и многое другое.
****

****
Проект *OpenSearch* был впервые анонсирован в январе 2021 года как ответвление *Elasticsearch* и *Kibana* с открытым исходным кодом для создания безопасного, высококачественого набора инструментов для поиска и аналитики. В июле 2021 года проект выпустил *OpenSearch 1.0* под лицензией *Apache*, версия 2.0 (ALv2), с кодом, доступным на *GitHub* и открытой для сообщества *OpenSearch*. Подробная дорожная карта проекта хранится link:https://github.com/orgs/opensearch-project/projects/1[*здесь*, window=_blank].
****

****
С момента запуска проекта сообщество *OpenSearch* количество участников сильно выросло. Множество выявленных и решенных проблем. В ноябре 2022 года *OpenSearch* выпустила версию 2.4 проекта с введением дистрибутивов *Windows* и улучшений отказоустойчивости кластера, функций поиска, инструментов аналитики и многого другого.
****

====
NOTE: Последняя версия *OpenSearch* доступна для скачивания link:https://opensearch.org/downloads.html[*здесь*, window=_blank].
====

****
Как решение с полностью открытым исходным кодом, *OpenSearch* позволяет изменять, расширять, монетизировать и перепродавать продукт по своему усмотрению, а также гибкость в развертывании в разных окружениях. В то же время проект *OpenSearch* предоставляет безопасный, высококачественный набор инструментов для поиска и аналитики с богатым набором новых и инновационных функций.
****

****
*OpenSearch* создан с учетом ваших пожеланий. Проект поддерживается и продвигается сообществом и сетью партнеров. Проект открыт для участия.
****