---
title: "Система поиска OpenSearch"
description: "Система поиска OpenSearch"
weight: 5
draft: false
---

:imgdir: /02_02_01_05_img/
:imagesoutdir: ./static/02_02_01_05_img/

include::content/init.adoc[]

= Система поиска OpenSearch

{empty} +

****
*OpenSearch* — это система поиска и аналитики с открытым исходным кодом, используемая разработчиками для получения, поиска, визуализации и анализа данных. *OpenSearch* состоит из хранилища данных и поисковой системы (*OpenSearch*), визуализации и пользовательского интерфейса (*OpenSearch Dashboards*), а так же сборщика данных на стороне сервера (*Data Prepper*). Пользователи могут предоставить доступ к функциональности *OpenSearch* с помощью набора подключаемых модулей, улучшающих поиск, аналитику, безопасность и многое другое.
****

****
Проект *OpenSearch* был впервые анонсирован в январе 2021 года как ответвление *Elasticsearch* и *Kibana* с открытым исходным кодом для создания безопасного, высококачественого набора инструментов для поиска и аналитики. В июле 2021 года проект выпустил *OpenSearch 1.0* под лицензией *Apache*, версия 2.0 (ALv2), с кодом, доступным на *GitHub* и открытой для сообщества *OpenSearch*. Подробная дорожная карта проекта хранится link:https://github.com/orgs/opensearch-project/projects/1[*здесь*, window=_blank].
****

****
С момента запуска проекта сообщество *OpenSearch* количество участников сильно выросло. Множество выявленных и решенных проблем. В ноябре 2022 года *OpenSearch* выпустила версию 2.4 проекта с введением дистрибутивов *Windows* и улучшений отказоустойчивости кластера, функций поиска, инструментов аналитики и многого другого.
****

====
NOTE: Последняя версия *OpenSearch* доступна для скачивания link:https://opensearch.org/downloads.html[*здесь*, window=_blank].
====

****
Как решение с полностью открытым исходным кодом, *OpenSearch* позволяет изменять, расширять, монетизировать и перепродавать продукт по своему усмотрению, а также гибкость в развертывании в разных окружениях. В то же время проект *OpenSearch* предоставляет безопасный, высококачественный набор инструментов для поиска и аналитики с богатым набором новых и инновационных функций.
****

****
*OpenSearch* создан с учетом ваших пожеланий. Проект поддерживается и продвигается сообществом и сетью партнеров. Проект открыт для участия.
****