[plantuml%interactive,"service",format=svg,align=center,width=75%]
.Service - Сервис
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(experience, "Experience", "Прикладные методы", $link="/05_c4/02_experience/")

System(service, "Service", "Сервис")
System(service_node, "Service", "Сервис", $link="/05_c4/02_experience/04_service/01_service_node/")
System(mes, "MES", "MES", $link="/05_c4/02_experience/04_service/02_mes/")

Rel_D(experience, service, "")
Rel_D(service, service_node, "")
Rel_D(service, mes, "")

@enduml
----
