[plantuml%interactive,"pforms",format=svg,align=center,width=30%]
.Print forms - Печатные формы
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(printservice, "Print forms", "Сервис печатных форм", $link="/05_c4_workflow/01_core/11_printservice/")
System(pforms, "Print forms", "Печатные формы")

Rel_U(pforms, printservice, "")

@enduml
----
