[plantuml%interactive,"insurance",format=svg,align=center,width=30%]
.Insurance - Страхование
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(f_and_i, "F&I", "Страхование и финансовые продукты", $link="/05_c4/02_experience/01_f_and_i/")
System(insurance, "Insurance", "Страхование")

Rel_U(insurance, f_and_i, "")

@enduml
----

