[plantuml%interactive,"rolfid",format=svg,align=center,width=75%]
.RolfID - Сотрудники, пользователи, ДЦ
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")
System(rolfid, "RolfID", "Сотрудники, пользователи, ДЦ")
System(users, "Users", "Пользователи", $link="/05_c4_workflow/01_core/06_rolfid/01_users/")
System(employees, "Employees", "Служащие", $link="/05_c4_workflow/01_core/06_rolfid/02_employees/")
System(dealerships, "Dealerships", "Дилерский центр", $link="/05_c4_workflow/01_core/06_rolfid/03_dealerships/")

Rel_D(core, rolfid, "")
Rel_D(rolfid, users, "")
Rel_D(rolfid, employees, "")
Rel_D(rolfid, dealerships, "")

@enduml
----
