---
title: "База данных PostgreSQL"
description: "База данных PostgreSQL"
weight: 2
draft: false
Categories:
    - Architecture
    - Backend
Tags:
    - Databases
    - PostgreSQL
---

:imgdir: /04_02_02_02_img/
:imagesoutdir: ./static/04_02_02_02_img/

include::static/includes/init.adoc[]



= База данных PostgreSQL

{empty} +

== Доступы PostgreSQL

=== DEV кластер

++++
<style>
.scrollable {
    overflow-x: auto;
}
</style>
++++

****
[.scrollable]
--
[%header, cols=".^1,.^1,.^1,.^1,.^1,.^1,.^1,.^1,.^1,.^1,.^1,.^1"]
|===
6+^.^| *Для работы с Dbeaver и PGadmin* 2+^.^| *Для работы Platformeco, канал COREAPP* 2+^.^| *Для работы Platformeco, канал INTEGRATION* 2+^.^| *Для работы Platformeco, канал ROLFID*
^.^| *host* ^.^| *port* ^.^| *sslmode* ^.^| *dbname* ^.^| *user* ^.^| *pass* ^.^| *пути в vault* ^.^| *юзер и пароль хранятся в vault* ^.^| *пути в vault* ^.^| *юзер и пароль хранятся в vault* ^.^| *пути в vault* ^.^| *юзер и пароль хранятся в vault*
| `[.blue]#c-c9qfus7o1luddvo41und.rw.mdb.yandexcloud.net#` | `6432` | `verify-full` | `onerolf-debug` | `onerolf` | `&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;` | `platformeco/data/coreapp/dev/debug` .6+| `HC_VAULT_ROLE_ID f8049c89-6286-8bb9-2f12-d8300b847d18
HC_VAULT_SECRET_ID f5d5004e-5853-a31d-b64b-f39742a1e40f` | `platformeco/data/integration/dev/debug` .6+| `HC_VAULT_ROLE_ID: 1598cded-3050-ca0a-ed44-ff394e0483f2
HC_VAULT_SECRET_ID: e2c22d6a-f531-6705-807d-088afe4020bc` | `platformeco/data/rolfid/dev/debug` .6+| `HC_VAULT_ROLE_ID: 10051677-c471-9d6a-aa4f-421c80dc52b8  
HC_VAULT_SECRET_ID: 10e3effd-c5ce-afeb-0341-93ba57b12838`
| `[.blue]#c-c9qfus7o1luddvo41und.rw.mdb.yandexcloud.net#` | `6432` | `verify-full` | `onerolf-test` | `onerolf` | `&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;` | `platformeco/data/coreapp/dev/test` | `platformeco/data/integration/dev/test` | `platformeco/data/rolfid/dev/test`
| `[.blue]#c-c9qfus7o1luddvo41und.rw.mdb.yandexcloud.net#` | `6432` | `verify-full` | `onerolf-dev`    |`onerolf`  |`&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;`  | `platformeco/data/coreapp/dev/develop` | `platformeco/data/integration/dev/develop` | `platformeco/data/rolfid/dev/develop`
| `[.blue]#c-c9qfus7o1luddvo41und.rw.mdb.yandexcloud.net#` | `6432` | `verify-full` |  `onerolf-preprod`    | `onerolf` | `&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;` | `platformeco/data/coreapp/dev/preprod` | `platformeco/data/integration/dev/preprod` | `platformeco/data/rolfid/dev/preprod`
| `[.blue]#c-c9qfus7o1luddvo41und.rw.mdb.yandexcloud.net#` | `6432` | `verify-full` | `pforms-dev` | `pforms-dev-readonly` | `&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;` |  |  | 
| `[.blue]#c-c9q78q89b7uqg831ek9l.rw.mdb.yandexcloud.net#` | `6432` |  |   `onerolf-prod`    |  |  |  |  | 
| `[.blue]#c-c9q78q89b7uqg831ek9l.rw.mdb.yandexcloud.net#` |  |             |     |  |  |  |  | 
|===
--

{empty} +

.Доступ к новым базам *Flora*
*****
*User:*
====
* `flora-debug`
* `flora-dev`
* `flora-preprod`
* `flora-prod`
====

*Пути в Vault:*
====
* `[.blue]#platformeco/<channel>/dev/debug/pgPass#`
* `[.blue]#platformeco/<channel>/dev/develop/pgPass#`
* `[.blue]#platformeco/<channel>/dev/preprod/pgPass#`
* `[.blue]#platformeco/<channel>/prod/production/pgPass#`
====
*****
****

=== PROD кластер

****
[%header, cols="^.^55,^.^15,^.^15,^.^15"]
|===
| Host | Port | sslmode | dbname

<.| `[.blue]#c-c9q78q89b7uqg831ek9l.rw.mdb.yandexcloud.net#` | `6432` | `verify-ful` | `onerolf-prod`
|===
****

== PostgreSQL

****
link:https://www.postgresql.org/[*PostgreSQL*, window=_blank] — объектно-реляционная система управления базами данных.
****

=== Преимущества PostgreSQL

====
. Поддержка *БД* неограниченного размера
. Мощные и надёжные механизмы транзакций и репликации
. Расширяемая система встроенных языков программирования и поддержка загрузки *C*-совместимых модулей
. Наследование
. Легкая расширяемость
====

=== Текущие ограничения PostgreSQL

====
. Нет ограничений на максимальный размер базы данных
. Нет ограничений на количество записей в таблице
. Нет ограничений на количество индексов в таблице
. Максимальный размер таблицы — *32* Тбайт
. Максимальный размер записи — *1,6* Тбайт
. Максимальный размер поля — *1* Гбайт
. Максимум полей в записи *250—1600* (в зависимости от типов полей)
====

=== Особенности PostgreSQL

****
Функции в *PostgreSQL* являются блоками кода, исполняемыми на сервере, а не на клиенте *БД*. Хотя они могут писаться на чистом *SQL*, реализация дополнительной логики, например, условных переходов и циклов, выходит за рамки собственно *SQL* и требует использования некоторых языковых расширений. Функции могут писаться с использованием различных языков программирования. *PostgreSQL* допускает использование функций, возвращающих набор записей, который далее можно использовать так же, как и результат выполнения обычного запроса. Функции могут выполняться как с правами их создателя, так и с правами текущего пользователя. Иногда функции отождествляются с хранимыми процедурами, однако между этими понятиями есть различие.
****

==== Триггеры

****
Триггеры в *PostgreSQL* определяются как функции, инициируемые DML-операциями. Например, операция *INSERT* может запускать триггер, проверяющий добавленную запись на соответствия определённым условиям. При написании функций для триггеров могут использоваться различные языки программирования. Триггеры ассоциируются с таблицами. Множественные триггеры выполняются в алфавитном порядке.
****

==== Механизм правил

****
Механизм правил в *PostgreSQL* представляет собой механизм создания пользовательских обработчиков не только *DML*-операций, но и операции выборки. Основное отличие от механизма триггеров заключается в том, что правила срабатывают на этапе разбора запроса, до выбора оптимального плана выполнения и самого процесса выполнения. Правила позволяют переопределять поведение системы при выполнении *SQL*-операции к таблице.
****

==== Индексы

****
Индексы в *PostgreSQL* следующих типов: *B*-дерево, *хэш*, *R*-дерево, *GiST*, *GIN*. При необходимости можно создавать новые типы индексов, хотя это далеко не тривиальный процесс.
****

==== Многоверсионность

****
Многоверсионность поддерживается в *PostgreSQL* — возможна одновременнуя модификация БД несколькими пользователями с помощью механизма **M**ulti**V**ersion **C**oncurrency **C**ontrol (*MVCC*). Благодаря этому соблюдаются требования *ACID*, и практически отпадает нужда в блокировках чтения.
****

==== Расширение

****
Расширение *PostgreSQL* для собственных нужд возможно практически в любом аспекте. Есть возможность добавлять собственные преобразования типов, типы данных, домены (пользовательские типы с изначально наложенными ограничениями), функции (включая агрегатные), индексы, операторы (включая переопределение уже существующих) и процедурные языки.
****

==== Наследование

****
Наследование в *PostgreSQL* реализовано на уровне таблиц. Таблицы могут наследовать характеристики и наборы полей от других таблиц (родительских). При этом данные, добавленные в порождённую таблицу, автоматически будут участвовать (если это не указано отдельно) в запросах к родительской таблице.
****