---
title: "OEM"
slug: "03_oem"
weight: 2
---

:toc: auto
:toc-title: Содержание
:toclevels: 5
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_03_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_03_img/

= OEM

{empty} +

====
NOTE: Описание раздела *OEM* будет добавлено позднее.
====

////
++++
<div id="editor-area" style="height: 600px"></div>

<script src="/drakonwidget.js"></script>

<script language="javascript">

var drakon = createDrakonWidget();

function buildConfig() {
    var config = {
        //startEditContent: startMyContentEditor, // My function
        //showContextMenu: showMyContextMenu, // My function
        //translate: tr, // My function
        //drawZones: false,
        //canSelect: true,
        //maxWidth: 300,
        //theme: {
        //   lineWidth: 1,
        //   background: "#afddfa",
        //    iconBorder: "#b0c0e0",
        //    iconBack: "white",
        //    shadowColor: "rgba(0, 0, 50, 0.15)",
        //    icons: {
        //        "question": {
        //           iconBack: "blue",
        //            iconBorder: "black",
        //          borderWidth: 0,
        //            color: "yellow"
        //        }
        //    }
        //}
    }

    return config;
}

function rebuildWidgetElement() {
    var editorArea = document.getElementById("editor-area");
    var rect = editorArea.getBoundingClientRect();
    editorArea.innerHTML = "";
    var config = buildConfig();
    var widgetElement = drakon.render(
        rect.width,
        rect.height,
        config
    );
    // alert(editorArea);
    editorArea.appendChild(widgetElement);
}

function createEditSender() {
    return {
        stop: function () { },
        pushEdit: function(edit) { console.log(edit) }
    }
}

var diagram = {
    id: "Minimal",
    name: "Minimal",
    access: "write",
    params: "param1\nparam2",
    style: "{\"background\":\"grey\"}",
    items: {
        "1": {
            type: "end"
        },
        "2": {
            type: "branch",
            branchId: 0,
            one: "3"
        },
        "3": {
            type: "action",
            content: "Hello!",
            one: "1",
            style: "{\"color\":\"yellow\"}"
        }
    }
}

var diagram2 = {
    id: "diag1",
    name: "diag1",
    access: "write",
    type: "drakon",
    params: "param1\nparam2",
    style: "{\"background\":\"grey\"}",    
    items: {
        "1": {
            id: "1",
            type: "beginend",
            isLine: false,
            x: 310,
            y: 100,
            w: 70,
            h: 20,
            content: {
                "txt": "diag1",
                "txt2": "",
                "font": "bold 22px 'Liberation Sans'"
            },
            role: "header"
        },
        "2": {
            id: "2",
            type: "end",
            isLine: false,
            x: 310,
            y: 510,
            w: 40,
            h: 20,
            content: {
                txt: "End",
                txt2: ""
            }
        },
        "4": {
            id: "4",
            type: "action",
            isLine: false,
            x: 480,
            y: 100,
            w: 70,
            h: 20,
            role: "params"
        },
        "6": {
            id: "6",
            type: "comment",
            isLine: false,
            x: 310,
            y: 205,
            w: 100,
            h: 25,
            content: {
                txt: "kjhgkjgh",
                txt2: ""
            }
        }
    },
    "edges": {
        "5": {
            id: "5",
            type: "horizontal",
            isLine: true,
            isVertical: false,
            head: "1",
            tail: "4"
        },
        "7": {
            id: "7",
            type: "vertical",
            isLine: true,
            isVertical: true,
            head: "1",
            tail: "6",
            role: "down"
        },
        "12": {
            id: "12",
            type: "vertical",
            isLine: true,
            isVertical: true,
            head: "6",
            tail: "2",
            role: "down"
        }
    },
    background: "",
    diaLine: "",
    diaLineThickness: "",
    font: "14px 'Liberation Sans'",
    version: 20180619,
    free: {
        "13": {
            id: "13",
            type: "callout",
            x: 510,
            y: 340,
            w: 100,
            h: 30,
            content: {
                txt: "",
                txt2: "",
                h0x: -130,
                h0y: -110
            },
            free: true
        }
    }
}

// var diagram = getDiagramFromServer(diagramId);
// drakon.setDiagram(diagramId, diagram, sender);

function ready() {
    var sender = createEditSender();

    drakon.setDiagram("Minimal", diagram, sender);
    drakon.setDiagram("diag1", diagram2, sender);
    rebuildWidgetElement();
    drakon.redraw();
}

document.addEventListener("DOMContentLoaded", ready);


</script>

++++
////