@startuml C1

'!pragma layout elk

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml
!include static/includes/c4_component.puml

skinparam backgroundcolor transparent
skinparam minClassWidth 150
skinparam wrapWidth 150
skinparam linetype ortho

LAYOUT_LEFT_RIGHT()

AddRelTag("DataBase", $textColor="blue", $lineColor="blue", $lineStyle=BoldLine())
AddRelTag("REST", $textColor="green", $lineColor="green", $lineStyle=BoldLine())
AddRelTag("Async", $textColor="plum", $lineColor="plum", $lineStyle=BoldLine())
AddRelTag("WebSocket", $textColor="orange", $lineColor="orange", $lineStyle=BoldLine())
AddRelTag("HTTP", $textColor="black", $lineColor="black", $lineStyle=BoldLine())

System_Boundary(ext_systems1, "Внешние системы") {
    System_Ext(elt, "ELT", "", $sprite="img:./static/05_02_img/elt_logo.png{scale=0.5}")
    System_Ext(dadata, "DaData.ru", "", $sprite="img:./static/05_02_img/dadata_logo.png{scale=0.1}")
    System_Ext(tinkoff, "Tinkoff", "", $sprite="img:./static/05_02_img/tinkoff_logo.png{scale=0.125}")
    System_Ext(autoteka_ru, "Autoteka.ru", "", $sprite="img:./static/05_02_img/autoteka_ru.png{scale=0.35}")
    System_Ext(rosbank, "Rosbank", "", $sprite="img:./static/05_02_img/rosbank.png{scale=0.15}")
}

System_Boundary(ext_systems2, "Внешние системы") {    
    System_Ext(e_credit, "Е-кредит", "", $sprite="img:./static/05_02_img/e_credit.png{scale=0.125}")
    System_Ext(auto_ru, "Auto.ru", "", $sprite="img:./static/05_02_img/auto_ru.png{scale=0.1}")
    System_Ext(kia_myservice, "KIA MyService", "", $sprite="img:./static/05_02_img/kia_myservice.png{scale=0.0375}")
    System_Ext(focus_kontur, "Контур Фокус", "", $sprite="img:./static/05_02_img/focus_kontur.png{scale=0.2}")
    System_Ext(sber, "Сбер", "", $sprite="img:./static/05_02_img/sber.png{scale=0.05}")
}

System_Boundary(rolf, "Рольф") {
    Person(user, "USER", "Пользователь")
    Person(admin, "ADMIN", "Администратор")

    System(flora, "FLORA", "", $sprite="img:./static/05_02_img/rolf_logo_2020.png{scale=0.2}", $link="/05_c4_schemes/02_c4_infrastructure/01_flora/")

    System_Boundary(payments_acquiring, "Платежный эквайринг") {
        System(atol, "Atol", "", $sprite="img:./static/05_02_img/kkm.png{scale=0.5}")
        System(kkm, "ККМ", "", $sprite="img:./static/05_02_img/kkm.png{scale=0.5}")
        System(payment_gateway, "Платежный шлюз", "", $sprite="img:./static/05_02_img/payment_gateway.png{scale=0.5}")
        System(1c_rose, "1C Rose", "", $sprite="img:./static/05_02_img/1c.png{scale=0.5}")
    }

    System(erl, "ERL", "Единый рабочий лист", $sprite="img:./static/05_02_img/oracle.png{scale=0.75}")
    System(smtp_server, "SMTP Server", "", $sprite="img:./static/05_02_img/smtp_server.png{scale=0.5}")
    System(sms_gateway, "SMS Шлюз", "", $sprite="img:./static/05_02_img/sms_gateway.png{scale=0.5}")
    System(ad, "Active Directory", "", $sprite="img:./static/05_02_img/ad.png{scale=0.3}")
    System(1c_arms, "1С АРМС", "", $sprite="img:./static/05_02_img/1c.png{scale=0.5}")
    System(saphr, "", "", $sprite="img:./static/05_02_img/sap_hr_logo.png{scale=0.075}")
    System(wms, "", "", $sprite="img:./static/05_02_img/wms_logo.png{scale=0.5}")
    System(mdm, "MDM", "", $sprite="img:./static/05_02_img/mdm.png{scale=0.5}")

    System_Boundary(opersystems, "Оперсистемы") {
        System(fishblue, "FishBlue", "", $sprite="img:./static/05_02_img/oracle.png{scale=0.75}")
        System(is_storm, "ИС Шторм", "", $sprite="img:./static/05_02_img/oracle.png{scale=0.75}")
        System(as_rolf, "АС Рольф", "", $sprite="img:./static/05_02_img/oracle.png{scale=0.75}")
        System(as_rolf_insurance, "АС Рольф Страхование", "", $sprite="img:./static/05_02_img/oracle.png{scale=0.75}")
    }

    Rel(user, flora, "", $tags="REST")
    Rel(admin, flora, "", $tags="REST")

    BiRel_D(flora, atol, "")
    BiRel_D(flora, kkm, "")
    BiRel_D(flora, payment_gateway, "")
    BiRel_D(flora, 1c_rose, "")

    BiRel_D(flora, erl, "", $tags="DataBase")
    BiRel_D(flora, smtp_server, "")
    BiRel_D(flora, sms_gateway, "")
    BiRel_D(flora, ad, "")

    BiRel_U(flora, 1c_arms, "")
    BiRel_U(flora, saphr, "")
    BiRel_U(flora, wms, "")
    BiRel_U(flora, mdm, "")
    BiRel_U(flora, fishblue, "", $tags="DataBase")
    BiRel_U(flora, is_storm, "", $tags="DataBase")
    BiRel_U(flora, as_rolf, "", $tags="DataBase")
    BiRel_U(flora, as_rolf_insurance, "", $tags="DataBase")
}

BiRel_D(flora, elt, "", $tags="HTTP")
BiRel_R(flora, dadata, "", $tags="HTTP")
BiRel_R(flora, tinkoff, "", $tags="HTTP")
BiRel_R(flora, autoteka_ru, "", $tags="HTTP")
BiRel_R(flora, rosbank, "", $tags="HTTP")

BiRel_U(flora, e_credit, "", $tags="HTTP")
BiRel_L(flora, auto_ru, "", $tags="HTTP")
BiRel_L(flora, kia_myservice, "", $tags="HTTP")
BiRel_L(flora, focus_kontur, "", $tags="HTTP")
BiRel_L(flora, sber, "", $tags="HTTP")

SHOW_LEGEND()

@enduml