---
title: "Сервис корректировки данных DaData"
description: "Сервис корректировки данных DaData"
weight: 1
draft: false
---

:imgdir: /02_02_03_01_img/
:imagesoutdir: ./static/02_02_03_01_img/

include::content/init.adoc[]

= Сервис корректировки данных DaData

{empty} +

****
image:dadata-logo.svg[150, 150, float="left"] Сервис *DaData.ru* приводит в порядок контактные данные: *Адреса*, *Ф.И.О.*, *Телефоны*, *Реквизиты Юрлиц*, *Email-s*. Вычищает из баз опечатки и дубли, дополняет открытыми данными. Готовит контакты для доставки, рассылок, обзвонов, аналитики.
****

.Преимущества:
****
* Сервис нужен, чтобы не проверять данные клиентов и контрагентов вручную. Контакты, обработанные *Dadata*, сразу отправляют в дело.
* Письма и посылки чаще доходят до получателей. Потому что для каждого адреса сервис исправляет ошибки и находит верный почтовый индекс.
* Обзвоны охватывают больше клиентов. «Дадата» вычищает опечатки из номеров и проставляет часовой пояс — чтобы не звонить ночами.
* Контрагенты без проблем оплачивают счета. Сервис по ИНН или названию проверяет реквизиты ИП и юрлица.
* Клиенты получают адресные и «теплые» емейлы. «Дадата» убирает ошибки из ФИО и склоняет: «Никифорову Алексею», «Никифорова Алексея», «Никифоровым Алексеем».
* Курьеры приезжают точно по адресу, не блуждая. Сервис определяет адрес пользователя по координатам.
****

.*Dadata* работает по трем направлениям:
****
. *Подсказки*. Их встраивают в электронные формы, чтобы пользователи сразу вводили данные без ошибок.
. *Стандартизация*. Исправляет и дополняет данные, которые уже собрали в базу.
. *Дедупликация*. Чистит готовые базы от дублей. Ищет пересечения в списках клиентов.
****

.Дополнительные возможности сервиса:
****
* Для адреса найдет координаты и ближайшие станции метро с расстояниями;
* Для квартиры покажет площадь и цену, для телефона — регион и сотового оператора;
* По *ИНН* выяснит долги юрлица и его систему налогообложения;
* Для емейла определит тип — личный или рабочий;
* По коду выдавшего паспорт подразделения подскажет полное название;
* *Ф.И.О.* разобьет на компоненты и определит пол,
* По *IP*-адресу определит город клиента;
* Удалит дубли из списка торговых точек дистрибьютора;
* Для каждого контакта проставит код качества.
****

****
Сервис применяют банки, мобильные операторы, интернет-магазины и производители федерального уровня. А вместе с ними — малый и средний бизнес. *Dadata* используют больше *5000* компаний и *46000* частных лиц.
****