---
title: "Сервер обмена сообщениями Centrifugo"
description: "Сервер обмена сообщениями Centrifugo WSS Server"
weight: 2
draft: false
---

:imgdir: /02_02_04_02_img/
:imagesoutdir: ./static/02_02_04_02_img/

include::content/init.adoc[]

= Centrifugo WSS Server

{empty} +

== Доступы Centrifugo

****
[cols=".^30h,.^70"]
|===
| Документация | `[.blue]#https://centrifugal.dev/#`
| url | `[.blue]#https://centrifugo.com-dev.int.rolfcorp.ru#`
| admin-url | `[.blue]#https://admin-centrifugo.com-dev.int.rolfcorp.ru#`
| admin-pass | `f703c86a-72e9-4fff-8f6a-d21c9994514f`
| apiKey | `011cc3b6-941f-41bc-ae71-4462d5f189e9`
| Token (может истечь со временем) | eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0YWdlcyIsImV4cCI6MTY4MDUxNTA4MCwiaWF0IjoxNjc5OTEwMjgwfQ.ntEXAJJArgBlIdIVfZ8QYq9uj-sLykrrhAfeAT1W64c 
|===
****

== Centrifugo

****
image:logo_animated_no_accel.svg[100, 100, float="left"] *Centrifugo* — это масштабируемый сервер обмена сообщениями в реальном времени с открытым исходным кодом. *Centrifugo* может мгновенно доставлять сообщения онлайн-пользователям приложения, подключенным через поддерживаемые транспорты (*WebSocket*, *HTTP-streaming*, *SSE/EventSource*, *WebTransport*, *GRPC*, *SockJS*). *Centrifugo* имеет концепцию канала — так что это сервер *PUB/SUB*, обращенный к пользователю. *Centrifugo* не зависит от языка и может использоваться для создания чат-приложений, *_живых_* комментариев, многопользовательских игр, визуализации данных в реальном времени, инструментов для совместной работы и т.д. в сочетании с любым бэкендом. Он хорошо подходит для современных архитектур и позволяет отделить бизнес-логику от транспортного уровня.
****

****
Несколько официальных клиентских *SDK* для разработки браузеров и мобильных устройств поддерживают двунаправленный протокол. Кроме того, *Centrifugo* поддерживает однонаправленный подход для простых случаев использования без зависимости от *SDK*.
****

****
*Centrifugo* впервые появился десять лет назад без встроенной поддержки параллелизма. В этом случае осуществляется работа с постоянными подключениями — это проблема, которую можно решить только внеся изменения в стек технологий и потратив время на создание готового к работе решения.
****

****
Например, такие фреймворки, как *Django*, *Flask*, *Yii*, *Laravel*, *Ruby* on *Rails* и другие, имеют плохую или неэффективную поддержку работы с постоянными соединениями для задач обмена сообщениями в реальном времени.
****

****
В этом случае *Centrifugo* — это простой способ осуществлять обновления в реальном времени и обрабатывать множество постоянных подключений без серьезных изменений в архитектуре серверной части приложения. Разработчики могут продолжить писать серверную часть приложения на любимом языке и/или любой платформе, сохранив существующую архитектуру и просто позволив *Centrifugo* работать с постоянными соединениями и быть транспортным уровнем обмена сообщениями в реальном времени.
****

****
В наши дни *Centrifugo* предоставляет несколько современных и уникальных функций, которые могут упростить работу разработчика и сэкономить месяцы работы. Даже если серверная часть приложения реализует асинхронный подход. Одним из примеров является то, что *Centrifugo* имеет встроенную поддержку масштабируемости для обработки большого количества подключений и по-прежнему гарантировать, что подписчики канала на разных узлах *Centrifugo* получают все публикации.
****

****
*Centrifugo* хорошо вписывается в современные архитектуры и может быть универсальным компонентом независимо от стека технологий.
****