---
title: "Коммуникация (communications)"
description: "Работа с коммуникациями во Flora"
version: 1
additional:
    team: "Communications"
    author: ""
    service : "PLT Communications"
    maintainer: ""
    developer: ""
    status: "in_work"
    product_apim: "flora-communications"
    category_apim: "Communications"
    subscribers: ["Communications"]
draft: false
slug: ""
weight: 1
---

:imgdir: /05_01_01_04_01_img/
:imagesoutdir: ./static/05_01_01_04_01_img/

include::static/includes/init.adoc[]



Сущность [Коммуникация (communications)](https://doc-core-main.com-dev.int.rolfcorp.ru/02_info_model/01_crm/02_communication/) представляет факт взаимодействия с клиентом, зафиксированный во Flora.

== Основные свойства

*ТИП*ы коммуникации:

* *Фактическая* (коммуникация состоялась)
* *Запланированная* (не состоялась)

*ВИД*ы коммуникации:

* *Входящая* - клиент обратился в Рольф
* *Исходящая* - сотрудник Рольф является инициатором

*МЕТОДы*  коммуникации:

* *Визит* - клиент находится на ДЦ
* *Телефонный разговор* - коммуникация была по телефону
* СМС 
* Электронная почта
* Пуш-уведомление в мобильном приложении
* Обычная почта (документы в бумажном виде)
* Приёмка
* Выдача

*СТАТУСы* коммуникации:

* Фактическая:
** Выполнена (**completed**)
** Аут (**cancelled**)
* Запланированная
** Запланирована (**is_planned**)
** Просрочена (**expired**)
** В работе (**in_progress**)
** Выполнена (**completed**)
** Аут (**cancelled**)

== Информационная модель

```json
{
    "uuid" : "93304cea-a154-46c3-bbb0-091042fd81b5", // уникальный идентификатор в БД
    "ui_id" : "676dfe87", // Короткий идентификатор для UI. communication_number в БД
    "status" : { // Статус коммуникации. Определяется несколькими полями.
        "name": "expired",
        "name_ui": "Просрочена"
    },
    "initiated_by_client": true, // Определяет ВИД 
    "is_fact_not_plan": false, // Определяет ТИП 
    "is_cancelled": false, // определяет статус "Отменена".
    "date_begin": "2023-02-28 23:13:16.908 +0300", // Дата начала
    "date_finish": null, // Дата окончания. Может быть null только для запланированной
    "asterisk_cdr_uniqueid": "", // Ссылка на запись в 
    "communication_method": { // Определяет МЕТОД
        "uuid": "b63b19d2-3fe4-11ed-b878-0242ac120002",
        "name": "Визит",
        "legal_document_type_of_existance": "9c20f22c-3fe6-11ed-b878-0242ac120002"
    },
    "client" : { // Ссылка на клиента (ФЛ или ЮЛ)
        "uuid" : "5439b56e-9e9a-4cd8-90c2-f2393c2181f2"
    },
    "employee": { // Ссылка на сотрудника. Инициатор
        "uuid": "90db72a4-91e2-41f5-b6a3-f3fc4534fa62",
        "employee_group": {
            "uuid": null
        }
    },
    "client_persons": [ //
        {
            "uuid": "3e003bfc-455a-11ed-b878-0242ac120002",
            "method": {
                "uuid": "b63b19d2-3fe4-11ed-b878-0242ac120002"
            },
            "address_text": "Ленинский городской округ, Московская область, посёлок Развилка вл 17"
           
        }    
    ],
    "dealership": { // Ссылка на диллерский центр
        "uuid": "37ad986e-0f3b-65a4-a462-d3cee621f7df"
    },
    "rolf_employee": {
        "employee": {
            "uuid": "9a179d22-98f4-44c0-86b5-693efaf3e4a5"
        }
    },
    "rolf_persons": [ // Ссылка на исполнителя коммуникации
        {
            "uuid": "3e003bfc-455a-11ed-b878-0242ac120002",
            "method": {
                "uuid": "b63b19d2-3fe4-11ed-b878-0242ac120002"
            },
            "address_text": "Ленинский городской округ, Московская область, посёлок Развилка вл 17"
        }
    ],
    "needs_and_orders": [ // Ссылка на потребности и предложения, которые были обсуждены в ходе коммуникации
        {
            "uuid": "1eecf98e-39f3-4651-9b18-b1d76b27b204",
            "was_identified": true            
        }
    ],
    "legal_documents": [ // Ссылка на юридические документы, которые были получены в рамках. Может быть пустым
        {
            "uuid":"b4332a7a-5e64-4c28-b780-256a77f4c5bb" 
        }
    ]
}
```

== Методы

++++
{{% openapi source="/02_01_01_04_01_json/communication.json" %}}
++++

=== Примеры использования

=== Требуется для разработки
|===
| # п.п. | Метод | Endpoint | Description | Priority | Comments |
| ------ | ----- | -------- | ----------- | -------- | -------- |
|        |       |          |             |          |          |
|        |       |          |             |          |          |
|        |       |          |             |          |          |
|===
