[plantuml%interactive,"credit",format=svg,align=center,width=30%]
.Credit - Кредитование
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(f_and_i, "F&I", "Страхование и финансовые продукты", $link="/05_c4_workflow/02_experience/01_f_and_i/")
System(credit, "Сredit", "Кредитование")

Rel_U(credit, f_and_i, "")

@enduml
----

