[plantuml%interactive,"fetm",format=svg,align=center,width=30%]
.Fetm - Fetm
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(external_integrations "External integration", "Внешние интеграции", $link="/05_c4_workflow/01_core/09_external_integrations/")
System(fetm, "Fetm", "Fetm")

Rel_U(fetm, external_integrations, "")

@enduml
----
