---
title: MDM - Мастер данные
weight: 11
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_02_09_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_02_09_img/

{empty} +

Системы *MDM* (*Master Data Management* - управление мастер-данными) - это решения, предназначенные для управления *нормативно-справочной информацией* (*НСИ*). Целью внедрения систем *MDM* является обеспечение единства представления массивов *НСИ* во всех информационных системах и решение проблем несоответствия, несопоставимости и дублирования данных.

{empty} +

Данная статья описывает функционал *Backend*-а который участвует в активностях *MDM*. #Скорректировать предложение.#

{empty} +

====
*MDM* решает следующие задачи:

****
* Обеспечение консолидации данных из различных систем
* Централизованное хранение нормативно-справочной информации
* Поддержание достоверной, актуальной и непротиворечивой информации
* Контроль за целостностью и согласованностью данных
* Обеспечение единых процессов ведения нормативно-справочной информации
****

Ключевые возможности *MDM* систем:

****
* Поддержка множества интеграционных механизмов со сторонними информационными системами
* Поддержка механизмов контроля качества и нормализации данных
* Импорт и экспорт данных с поддержкой распространённых форматов
* Поддержка ролевого доступа к данным
* Поддержка расширяемых моделей данных
****
====

IMPORTANT: Знаком icon:minus-circle[role=red] отмечены активности которые не войдут в *MVP на МАРТ 2023 года!!!*

{empty} +

.*Решаемые задачи*
****
. *Создание/изменение/удаление справочной информации по автомобилям*
+
====
* Экспорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Импорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Ручная загрузка (занесение данных через интерфейс) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Интеграция с *Auto.ru* #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
* Дедубликация #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *Platformeco* - *MDM (автомобиль)*
====
+
. *Создание/изменение/удаление справочной информации по запчастям*
+
====
* Экспорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Импорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Ручная загрузка (занесение данных через интерфейс) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Интеграция с агрегатором #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
* Дедубликация #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *Platformeco* - *MDM (запчасти)*
====
+
. *Создание/изменение/удаление справочной информации по опциям*
+
====
* Экспорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Импорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Ручная загрузка (занесение данных через интерфейс) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Интеграция с агрегатором #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
* Дедубликация #Уточнить и описать серверный функционал участвующий в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

*Platformeco* - *MDM (опции)*
====
+
. *Создание/изменение/удаление справочной информации по работам*
+
====
* Экспорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Импорт (через файл CSV) #Уточнить и описать серверный функционал участвующий в этой активности!#
* Ручная загрузка (занесение данных через интерфейс) #Уточнить и описать серверный функционал участвующий в этой активности!#
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

*Platformeco* - *MDM (работы)*
====
+
. *Процессы согласования* icon:minus-circle[role=red]	
+
====
* Создание/изменение удаление процессов согласования внутри *MDM* #Уточнить и описать серверный функционал участвующий в этой активности!#
====
****