---
title: WMS - Система управления складом
weight: 12
---

:toc: auto
:toc-title: Содержание
:doctype: book
:icons: font
:figure-caption: Рисунок
:source-highlighter: pygments
:pygments-css: style
:pygments-style: monokai
:includedir: ./content/

:imgdir: /02_02_10_img/
:imagesdir: {imgdir}
ifeval::[{exp2pdf} == 1]
:imagesdir: static{imgdir}
:includedir: ../
endif::[]

:imagesoutdir: ./static/02_02_10_img/

{empty} +

*WMS-система управления складом* (Warehouse Management System) – система, предназначенная для автоматизации управления процессами склада и работы складского комплекса. +
Данная статья описывает функционал *Backend*-а (внутреннюю логику системы) которая участвует в активностях *WMS*.

{empty} +

IMPORTANT: Знаком icon:minus-circle[role=red] отмечены активности которые не войдут в *MVP на МАРТ 2023 года!!!*

{empty} +

.*Решаемые задачи*
****
. *Приемка автомобля с пробегом*
+
====
* Ключ #Уточнить и описать серверную функциональность участвующую в этой активности! (Получение ключа от владельца автомобиля, фиксация этого события и т.д.)#
* Колеса БУ #Уточнить и описать серверную функциональность участвующую в этой активности! (Получение колес от владельца автомобиля, фиксация этого события и т.д.)# icon:minus-circle[role=red]
* Предпродажная подготовка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Сервис #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Фото #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Мойка, химчистка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Заказ перевозчика #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Внутреннее перемещение #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Внешнее перемещение #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Чек-лист приемки АСП #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *АСП - WMS*: запрос на создание задачи по приемке после выкупа
* Синхронизация стока *Flora* и *WMS авто*
====
+
. *Приемка нового автомобиля*
+
====
* Внесение логистом НА в систему #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Заказ перевозчика, внесение данных о перевозке в систему #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Приемка в ДЦ Хранения #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Приемка в ДЦ Продажи #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Чек-лист повреждений по форме импортера #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Чек-лист на комплектность #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Запрос импортеру #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Перемещение на место хранения #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Чек-лист внешнего перемещения #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Получение/сдача ключа #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Предпродажная подготовка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Установка допов #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Сервис #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Интеграция с перевозчиками #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Интеграция с системами импортеров #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Электронная ключная #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
. *Выдача нового автомобиля*
+
====
* Ключ #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Электронная ключная #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Мойка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Химчистка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Внутреннее перемещени #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Подменки #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Тест-драйв #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *НА - WMS*: запрос на создание задачи по выдаче после подписания доков #Уточнить и описать серверную функциональность участвующую в этой активности!#
* *WMS - НА*: передача статуса “машина готова к выдаче“, чтобы ПК принял, подтвердил и отдал машину клиенту #Уточнить и описать серверную функциональность участвующую в этой активности!#
====
+
. *Выдача автомобиля с пробегом*
+
====
* Ключ #Уточнить и описать серверную функциональность участвующую в этой активности!# +
* Электронная ключная #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Мойка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Химчистка #Уточнить и описать серверную функциональность участвующую в этой активности!#
* Внутреннее перемещение #Уточнить и описать серверную функциональность участвующую в этой активности!#
====
+
====
*Интеграции внешние и внутренние:* #Переговорить с Константином Латеремом!!!#

* *АСП - WMS*: запрос на создание задачи по выдаче после подписания доков #Уточнить и описать серверную функциональность участвующую в этой активности!#
* *WMS - АСП*: передача статуса “машина готова к выдаче“, чтобы ПК принял, подтвердил и отдал машину клиенту #Уточнить и описать серверную функциональность участвующую в этой активности!#
====
+
. *Аудит* icon:minus-circle[role=red]
+
====
* Создание/изменение/удаление задач на разовый аудит #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Создание/изменение/удаление задач на регулярный аудит #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
. *Рекомендательная система по выбору парковки* icon:minus-circle[role=red]
+
====
* Создание/изменение/удаление правил рекомендательной системы #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
+
. *TMS Запчасти* icon:minus-circle[role=red]
+
====
* Приемка товарных единиц на склад #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Размещение товарных единиц на местах хранения #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Оптимизация размещения товарных единиц #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Сборка заказов #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Упаковка заказов перед отгрузкой #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
* Отгрузка заказов #Уточнить и описать серверную функциональность участвующую в этой активности!# icon:minus-circle[role=red]
====
****