---
title: "Радар технологий"
description: "Радар технологий"
weight: 6
draft: false
titleIcon: "fa-sharp fa-solid fa-radar"
slug: ""
Categories:
    - Techradar
Tags:
    - Techradar
---

:imgdir: /06_img/
:imagesoutdir: ./static/06_img/

include::static/includes/init.adoc[]

= Радар технологий

{empty} +

++++
<div class="specs">
    <a href="/06_techradar/01_frontend/"><button class="button-1">Frontend</button></a>
    <a href="/06_techradar/02_backend/"><button class="button-1">Backend</button></a>
    <a href="/06_techradar/03_quality_assurance/"><button class="button-1">Quality Assurance</button></a>
    <a href="/06_techradar/04_data_science/"><button class="button-1">Data Science</button></a>
    <a href="/06_techradar/05_infrastructure/"><button class="button-1">Infrastructure</button></a>
</div>
++++

{empty} +

****
Это карта технологий, которые допустимы в работе. С его помощью любой сотрудник компании может выбрать технологию, которую сможет использовать при разработке. Мы используем четыре кольца со следующей семантикой:
====
* *RESEARCH* - пробные технологии, которые в данный момент оцениваются. С их участием реализуются только тестовые проекты, и они не используются в реальных задачах.
* *TRIAL* - технологии, которые уже прошли этап тестирования и готовятся к тому, чтобы работать в производственной среде.
* *ADOPT* - технологии, в которых мы уверены, что они будут служить нашим целям, в том числе и в больших масштабах. Технологии с культурой использования в нашей производственной среде, низким уровнем риска и рекомендуемые к широкому использованию.
* *HOLD* - в этой категории у нас есть экспертиза, но упомянутые технологии используются только при поддержке существующих систем и новые проекты на них не запускаются.
====
****

== Какая цель?

****
Внедрения технологического радара заключается в том, чтобы выявить ответственных за рациональность используемого стека технологий и построить процесс их ввода и вывода из использования. Под технологиями здесь понимается все – языки, фреймворки, библиотеки, инструменты.
****

== Почему это важно?

****
* *Для лида* - Без контроля за тем, какие технологии используются, область ответственности может быстро выйти из под контроля. Лид обладает более широким контекстом, чем разработчики, чтобы оценить риски от внедрения новых технологий.
* *Для команды* - Если есть понятный процесс тестирования и внедрения новых технологий, это может быть хорошим кандидатом в качестве личных целей.
* *Для компании* - Упрощается унификация знаний между разными командами разработки и появляется возможность перебрасывать людей между командами. Снижается риск того, что важный компонент системы будет написан с использованием чего-то экзотического.
****

== Что будет, если этого не делать?

****
. Команда разработки будет внедрять новые технологии, исходя только из своей заинтересованности.
. Усложняется найм людей, так как на входе требуется больше знаний.
. Усложняется найм людей, так как им не будет интересно копаться в старых технологиях.
. Сложнее перекидывать людей между проектами и компаниями, так как навыки не будут универсальными.
. Система в целом становится менее поддерживаемой.
. Внедрение любых новых технологий может быть под запретом.
. Повышаются риски безопасности, так как больше мест для нахождения уязвимостей.
. Снижается мотивация существующей команды.
. Не используются более эффективные способы решения старых задач.
****

== Как начать использовать новую технологию

****
* *Этап 1 — Research* - Обращаемся в комитет и если добро дадут *50%* участников, то тестируем и оцениваем технологию. По результатам эксперимента рассказываем о проделанной работе на следующем собрании комитета.
* *Этап 2 — Trial* - Чтобы технология перешла в категорию *Trial* должны проголосовать *75%* участников комитета. Если нужного количества голосов не наберётся, мы удалим технологию из радара или продолжим исследование.
* *Этап 3 — Adopt* - Продолжаем использовать технологию. Если всё отлично, предлагаем комитету перенести технологию в категорию *Adopt*. Для этого нужно согласие *100%* участников комитета.
* *Этап 4 — Hold* - Если технология не подошла, переносим её в *Hold* и больше не используем. Для этого проверяем все системы на необходимость рефакторинга и исправления технического долга. Чтобы отказаться от технологии, должны проголосовать *100%* участников комитета.
****

****
Для перехода в *Trial* необходимо ответить на следующие пункты:
====
. *Владелец сервиса*
. *Наличие поддержки*
. *Контур*
. *Окружения сервиса*
. *Предполагаемая нагрузка*
. *Расположение артефактов*
. *Домены*
. *Сертификаты*
. *Конфигурации*
. *Ролевая модель*
. *Сетевое взаимодействие*
. *Кого аффектит и кто будет под это адаптироваться*
====
****

== Каналы общения с комитетом

****
* *Slack* — канал технологического комитета `#rolf-tech-radar`. Предназначен для общения между участниками комитета так и заинтересованными сотрудниками по новым технологиям. Здесь можно обозначить необходимость в новой технологии и запросить детали подготовки ко встречи.
* *Meet* — видео встреча по комитету проходит раз в 2 недели (создать расписание). Предназначена для обсуждения входящих запросов и голосованию по изменению статуса технологии. Состав участников не из комитета обсуждается до самой встречи.
****

== Состав технологического комитета

****
* *Frontend*
* *Backend*
* *Quality Assurance*
* *Data Science*
* *Infrastructure*
** Игорь Любимов
****

== Примечания

****
* Для изменения состава комитета или его правил необходимо одобрения *50%* участников комитета.
* У *СТО* есть право вето.
* Для запроса по новой технологии необходимо написать в чате развернутое обоснование с указанием целей и задач.
****