[plantuml%interactive,"payments",format=svg,align=center,width=20%]
.Payments - Платежи, чеки
----
@startuml

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")
System(payments, "Payments", "Платежи, чеки")
System(payment, "Payment", "Платеж", $link="/05_c4_workflow/01_core/02_payments/01_payment/")

Rel_D(core, payments, "")
Rel_D(payments, payment, "")

@enduml
----
