@startuml Flora

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml
!include static/includes/c4_component.puml

'!pragma layout elk
'!pragma layout smetana
'!pragma layout VizJs
'!pragma layout GraphViz

skinparam svgLinkTarget _blank
skinparam minClassWidth 200
skinparam wrapWidth 200
skinparam linetype ortho
'skinparam linetype polyline
skinparam backgroundColor transparent
'skinparam nodesep 150
'Skinparam Ranksep 150

LAYOUT_TOP_DOWN()

AddRelTag("DataBase", $textColor="blue", $lineColor="blue", $lineStyle=BoldLine())
AddRelTag("REST", $textColor="green", $lineColor="green", $lineStyle=BoldLine())
AddRelTag("Async", $textColor="plum", $lineColor="plum", $lineStyle=BoldLine())
AddRelTag("WebSocket", $textColor="orange", $lineColor="orange", $lineStyle=BoldLine())
AddRelTag("HTTP", $textColor="black", $lineColor="black", $lineStyle=BoldLine())


System(flora, "Flora", "Система Flora", $sprite="img:./static/06_01_img/rolf_logo_2020.png{scale=0.25}", $link="")

System_Boundary(core, "CORE", "Общий функционал"){

    System(printservice, "Print service", "Сервис печати", $sprite="img:./static/06_01_img/printservice.png{scale=0.5}", $link="")
        System(pforms, "Print forms", "Печатные формы", $sprite="img:./static/06_01_img/pforms.png{scale=0.5}")

    System(carid, "CarID", "Транспортные средства", $sprite="img:./static/06_01_img/carid.png{scale=0.5}", $link="")
        System(vehicles, "Vehicles", "Транспортные средства", $sprite="img:./static/06_01_img/vehicles.png{scale=0.5}")
    
    System(clientid, "ClientID", "Клиенты (физлица и организации)", $sprite="img:./static/06_01_img/client_card.png{scale=0.5}", $link="")
        System(clients, "Individuals", "Физлица", $sprite="img:./static/06_01_img/client_card.png{scale=0.5}")
        System(organizations, "Organisations", "Организации", $sprite="img:./static/06_01_img/company_card.png{scale=0.5}")
        System(companies, "Companies", "Компании", $sprite="img:./static/06_01_img/company_card.png{scale=0.5}")

    System(coreapp, "Coreapp", "Комментарии, датагриды", $sprite="img:./static/06_01_img/flora_core_app2.png{scale=0.5}", $link="")
        System(comments, "Comments", "Комментарии", $sprite="img:./static/06_01_img/comments.png{scale=0.5}", $link="")
        System(annotations, "Annotations", "Аннотации", $sprite="img:./static/06_01_img/annotation.png{scale=0.5}", $link="")
        System(datagrid, "Datagrids", "Базы данных и фильтры", $sprite="img:./static/06_01_img/datagrid.png{scale=0.5}", $link="")

    System(payments, "Payments", "Платежи, чеки", $sprite="img:./static/06_01_img/payments.png{scale=0.5}", $link="")
        System(check, "Сheck", "Чек", $sprite="img:./static/06_01_img/payments.png{scale=0.5}", $link="")
        
    System(needs_and_orders, "Needs and orders", "Обращения, потребности, предложения", $sprite="img:./static/06_01_img/orders.png{scale=0.5}", $link="")
        System_Boundary(legalexecution, "Legal execution", "Legal execution"){
            System(legaldocuments, "Legal documents", "Юридические документы", $sprite="img:./static/06_01_img/legal_document.png{scale=0.5}", $link="")
            System(legalevents, "Legal events", "Юридические события", $sprite="img:./static/06_01_img/legal_events.png{scale=0.5}", $link="")
        }

        System(orders, "Orders", "Заказы", $sprite="img:./static/06_01_img/orders.png{scale=0.5}", $link="")
        System(needs, "Needs", "Потребности", $sprite="img:./static/06_01_img/needs.png{scale=0.5}", $link="")
        System(carts, "Carts", "Пакет услуг", $sprite="img:./static/06_01_img/carts.png{scale=0.5}", $link="")

    System(communications, "CRM", "CRM", $sprite="img:./static/06_01_img/communications.png{scale=0.5}", $link="")
        System(communication, "Communications", "Коммуникации", $sprite="img:./static/06_01_img/communications.png{scale=0.5}", $link="")
        System(requests, "Requests", "Обращения", $sprite="img:./static/06_01_img/request.png{scale=0.5}", $link="")

    System(tasks_and_events, "Tasks and events", "Задачи, события и оповещения", $sprite="img:./static/06_01_img/task_and_events.png{scale=0.5}", $link="")
        System(tasklist, "Task list", "Список задач", $sprite="img:./static/06_01_img/tasklist.png{scale=0.5}", $link="")
            System(task, "Task", "Задача", $sprite="img:./static/06_01_img/task.png{scale=0.5}", $link="")
        System(notify, "Notify", "Уведомление", $sprite="img:./static/06_01_img/notify.png{scale=0.5}", $link="")
        System(events, "Events", "События и оповещения", $sprite="img:./static/06_01_img/event.png{scale=0.5}", $link="")

    System(rolfid, "RolfID", "Сотрудники, пользователи, ДЦ", $sprite="img:./static/06_01_img/rolfid.png{scale=0.5}", $link="")
        System(users, "Users", "Пользователи", $sprite="img:./static/06_01_img/users.png{scale=0.5}", $link="")
        System(dealerships, "Dealerships", "ДЦ", $sprite="img:./static/06_01_img/dc_card.png{scale=0.5}", $link="")
}

System_Boundary(experience, "EXPERIENCE", "Прикладные методы"){
    System(services, "Service", "Сервис", $sprite="img:./static/06_01_img/frontend_service.png{scale=0.5}", $link="")
        System(service, "Service", "Сервис", $sprite="img:./static/06_01_img/frontend_service.png{scale=0.5}", $link="")
        System(mes, "MES", "Сервис", $sprite="img:./static/06_01_img/mes.png{scale=0.5}", $link="")

    System(na, "NA Sale", "Продажа новых автомобилей", $sprite="img:./static/06_01_img/asp_sell.png{scale=0.5}", $link="")
    System(fi, "F&I", "F&I", $sprite="img:./static/06_01_img/fi.png{scale=0.5}", $link="")
    System(asp, "ASP", "Продажа подержанных автомобилей", $sprite="img:./static/06_01_img/asp_sell.png{scale=0.5}", $link="")
        System(asp_sale, "ASP Sale", "Продажа автомобиля с пробегом", $sprite="img:./static/06_01_img/asp_sell.png{scale=0.5}", $link="")
        System(asp_buyout, "ASP Buyout", "Выкуп автомобиля с пробегом", $sprite="img:./static/06_01_img/asp_sell.png{scale=0.5}", $link="")
}

' Relations

Rel_U(flora, services, "")
    Rel_U(services, service, "")
    Rel_U(services, mes, "")

Rel_U(flora, na, "")
Rel_U(flora, fi, "")

Rel_U(flora, asp, "")
    Rel_U(asp, asp_sale, "")
    Rel_U(asp, asp_buyout, "")

Rel_D(experience, core, "")

Rel_D(flora, printservice, "")
    Rel_D(printservice, pforms, "")

Rel_D(flora, carid, "")
    Rel_D(carid, vehicles, "")

Rel_D(flora, clientid, "")
    Rel_D(clientid, clients, "")
    Rel_D(clientid, organizations, "")
    Rel_D(clientid, companies, "")

Rel_D(flora, coreapp, "")
    Rel_D(coreapp, comments, "")
    Rel_D(coreapp, annotations, "")
    Rel_D(coreapp, datagrid, "")

Rel_D(flora, payments, "")
    Rel_D(payments, check, "")

Rel_D(flora, needs_and_orders, "")
    Rel_D(needs_and_orders, legaldocuments, "")
    Rel_D(needs_and_orders, legalevents, "")
    Rel_D(needs_and_orders, needs, "")
    Rel_U(orders, needs, "")
    Rel_D(needs_and_orders, carts, "")

Rel_D(flora, communications, "")
    Rel_D(communications, communication, "")
    Rel_D(communications, requests, "")

Rel_D(flora, tasks_and_events, "")
    Rel_D(tasks_and_events, tasklist, "")
        Rel_D(tasklist, task, "")
    Rel_D(tasks_and_events, events, "")
    Rel_D(tasks_and_events, notify, "")

Rel_D(flora, rolfid, "")
    Rel_D(rolfid, users, "")
    Rel_D(rolfid, dealerships, "")

' Layout

Lay_D(services, flora)

Lay_D(flora, printservice)
    Lay_D(printservice, pforms)

Lay_D(flora, carid)
    Lay_D(carid, vehicles)

Lay_D(flora, clientid)
    Lay_D(clientid, clients)
    Lay_D(clientid, organizations)

Lay_D(pforms, coreapp)
    Lay_D(coreapp, comments)
    Lay_D(coreapp, annotations)
    Lay_D(coreapp, datagrid)

Lay_D(vehicles, payments)
    Lay_D(payments, check)

Lay_D(comments, communications)
    Lay_D(communications, communication)
    Lay_D(communications, requests)

Lay_D(check, tasks_and_events)
    Lay_D(tasks_and_events, tasklist)
    Lay_D(tasks_and_events, events)

Lay_D(legaldocuments, rolfid)
    Lay_D(rolfid, users)
    Lay_D(rolfid, dealerships)

Lay_D(task, needs_and_orders)
    Lay_D(needs_and_orders, legaldocuments)
    Lay_D(needs_and_orders, legalevents)
    Lay_D(needs_and_orders, orders)
    Lay_D(needs_and_orders, needs)
    Lay_D(needs_and_orders, carts)


@enduml