[plantuml%interactive,"flora",format=svg,align=center,width=50%]
.Flora
----
@startuml

!include static/includes/c4_context.puml
!include static/includes/c4_container.puml
!include static/includes/c4_component.puml

'skinparam svgLinkTarget _blank
skinparam backgroundcolor transparent
skinparam minClassWidth 200

LAYOUT_TOP_DOWN()

System(flora, "Flora", "Система Flora")
System(core, "Core", "Общий функционал", $link="/05_c4_workflow/01_core/")
System(experience, "Experience", "Прикладные методы", $link="/05_c4_workflow/02_experience/")

Rel_D(flora, core, "")
Rel_D(flora, experience, "")

@enduml
----

